#!/usr/bin/env bash
# if emacs is running, the colors are derived from the currently running emacs session

colors() {
    color0=E8EBEC
    color1=006E96
    color2=007C00
    color3=C38418
    color4=0065C8
    color5=407EE7
    color6=C6007F
    color7=4A4D4E
    color8=6A6D6E
    color9=006E96
    color10=007C00
    color11=C38418
    color12=0065C8
    color13=407EE7
    color14=C6007F
    color15=4A4D4E

    foreground=4a4d4e
    background=e8ebec
    cursorColor=0065c8

    e_background_normal=e8ebec
    e_foreground_normal=4a4d4e
    e_faded_normal=6a6d6e
    e_primary_normal=c6007f
    e_alt_normal=006e96
    e_strings_normal=007c00
    e_assumed_normal=0065c8
    e_background_weak=d5d6d7
    e_foreground_weak=3f4041
    e_faded_weak=5f6061
    e_primary_weak=ba0073
    e_alt_weak=00668e
    e_strings_weak=007400
    e_assumed_weak=005dc0
    e_background_strong=ccc9ca
    e_foreground_strong=3a3738
    e_faded_strong=5a5758
    e_primary_strong=ac0065
    e_alt_strong=005e86
    e_strings_strong=006c00
    e_assumed_strong=0053b6
    e_background_focused=a4cfed
    e_foreground_focused=103b59
    e_faded_focused=305b79
    e_primary_focused=ac0065
    e_alt_focused=005e86
    e_strings_focused=006c00
    e_assumed_focused=0053b6

    if elisp t >/dev/null; then
        eval "$(elisp -r "(ns/emacs-to-theme)")"
    fi
}

settings() {
    # BG_COMMAND="feh --bg-tile /home/neeasade/git/neeasade.net/pattern_125.gif"
    # BG_COMMAND="hsetroot -solid $(elisp -r '(tarp/get :background :focused)')"
    # BG_COMMAND="hsetroot -solid #$e_background_focused"
    BG_COMMAND="${HOME}/.fehbg"
    # BG_COMMAND="hsetroot -solid $(elisp -r '(-> (tarp/get :assumed) (ct-transform-hsl-l (ct-get-hsl-l (tarp/get :background :weak))))')"
    # BG_COMMAND="feh --bg-tile /tmp/result.png"

    PROMPT_CHAR='%'
    # PROMPT_CHAR='♥'

    # bspwm
    b_border_width=8

    # b_normal_border_color=B0A8A6
    # b_normal_border_color=$(colort -t $(lessen 20 $color0))

    # b_normal_border_color=$(elisp -r "(ct-shorten (face-attribute 'mode-line-inactive :background))")
    # b_normal_border_color=$(colort -t "$b_normal_border_color")

    b_window_gap=32
    # b_window_width=10

    b_bspwmrc_extend="tag_borders &
subscription_rules &"

    x_padding=5

    # b_normal_border_color=eeeff0
    # b_active_border_color=cecece
    # b_focused_border_color=$(colort -b 20 -t $(lessen 10 $foreground))
    # b_focused_border_color=$(elisp -r '(face-attribute 'font-lock-variable-name-face :foreground)')

    # pastel variation might be nice here
    b_focused_border_color=$e_primary_focused

    # p_gap=$(elisp '(frame-fringe-width)')
    p_gap=0

    # elisp -r "(face-attribute 'region :background)"

    # p_bg_middle=$(elisp -r "(face-attribute 'ns/mode-line-inactive :background)")

    # p_format="org_task:title|tags|mpd:weather:clock"
    # p_format="tags:title|org_task|mpd:weather:clock"
    p_format="tags:title|org_task:misc|toots:mpd:org_time:clock"

    # p_format="battery|desktop|clock"

    p_title_show_mode=active         # used by title.

    p_height=22
    # p_gap=0
    p_window_class="noshadow"
    p_line=2
    # p_padding=6

    # st_font="Go Mono for Powerline-14"

    # st_font="Fira Code 16"
    st_font="Go Mono 16"
    # st_font_variable="Charter 14"
    st_font_variable="Go Mono 16"
    st_font_variable="Equity Text B-10"

    p_font_main="Charter-12"

    d_font="Charter 12"

    p_font_icon="Font Awesome 5 Free Solid-8"
    p_icon_enable=false
    p_desktop_display_name=name

    p_icon=$e_alt_normal

    # p_desktop_occupied_label=$(uchar f111)
    # p_desktop_empty_label=$(uchar f1db)

    p_desktop_tiling_label=''
    p_desktop_monocle_label=$(uchar f00b)

    p_title_only_show_active=true
    maxWinNameLen=40

    # p_title_theme="fg=#ff$(colort -t 30 525252)"
    # p_desktop_theme="fg=#ff$(colort -t 30 525252)"

    c_shadow="false"
    c_frame_opacity="1.0"
    c_shadow_opacity="0.5"
    c_shadow_radius="5"
    c_shadow_offset_x="-8"
    c_shadow_offset_y="-8"

    c_fading="false";
    c_fade_in_step="0.1"
    c_fade_out_step="0.1"
}

activeline() {
    activefg
}

line() {
    bg
}

fg() {
    if [ "$lemon_target_align" = center ]; then
	    elisp -r '(tarp/get :foreground :weak)'
    else
	    elisp -r '(tarp/get :foreground)'
    fi
}

bg() {
    if [ "$lemon_target_align" = center ]; then
	    elisp -r '(tarp/get :background :weak)'
    else
	    elisp -r '(tarp/get :background)'
    fi
}

stepSetup() {
    # togetherStep
    separateStep
}
