#!/usr/bin/env bash
# berry theme

BG_COMMAND="feh --bg-fill $HOME/.wm/walls/fill/berry.jpg"
emacs_theme=base16-atelier-forest

# bspwm
b_border_width=4
b_window_gap=16

# panel
p_gap=7
p_height=22
p_underline="5"
p_font_main="Droid Sans-10:style=Bold"
d_font="Droid Sans 10"

p_padding=2

p_window_class="noshadow"
p_offset=-1

p_title_only_show_active=true

p_desktop_display_format=separate
p_desktop_occupied_label="$(echo -n -e '\uf004')"
p_desktop_empty_label="$(echo -n -e '\uf08a')"

p_delimiter="   "

p_format="dropdown:mpd:title|desktop|themeSwitch:volume:updates:weather:clock"

# colors
#pBGInactiveTab="#99`echo "$pBG" | cut -c4-`"
p_bg_normal="#00$(colort -t $p_bg_normal)"

# other
GTK_FONT="Droid Sans 10"
