#!/usr/bin/env bash
# jellybean theme

# theme
VIM_COLORS=chameleon
BG_COMMAND="feh --bg-tile $HOME/.wm/walls/tiled/random_grey_variations.png"
emacs_theme=ujelly

# bspwm
b_border_width=1
b_window_gap=8

b_bspwmrc_extend="pulse.sh &"

# panel
p_height=20
p_font_main="tewi-8"
p_font_icon="Siji-8"
p_gap=4
p_underline=0

noModeToggle=true
p_padding=1
p_window_class=noshadow
p_offset=-2

p_desktop_display_name=name
p_desktop_show_free=false
p_desktop_only_active=true
p_title_only_show_active=false
p_position=bottom


# colors
p_fg_normal="#ffcccccc"
p_bg_active="$(colort 30 "$p_bg_normal")"
p_fg_active="$p_fg_normal"
p_fg_inactive="$p_fg_normal"
p_icon="$p_fg_normal"

# other
d_font="xos4 Terminus 8"

GTK_FONT="tewi 8"
st_font="tewi-8"
st_borderpx=4
st_cursorshape=3
st_cursorthickness=1
PROMPT_CHAR=\>

weechat_prefix_join=">"
weechat_prefix_quit="<"
weechat_separator_horizontal="-"
weechat_separator_vertical="|"
weechat_prefix_suffix="|"
weechat_input_items="[input_search],[input_paste],       >>>,input_text"


tmux_statusbar="$(cat <<EOF
setw -g window-status-current-fg colour170
setw -g window-status-current-bg colour239
setw -g window-status-current-attr bold
setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour170]#F '

setw -g window-status-fg colour138
setw -g window-status-bg colour236
setw -g window-status-attr none
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

set -g status-left ''
set -g status-justify centre
set-option -g status-position top
EOF
)"


p_format="dropdown:desktop|title|dynamicmpd:volume:updates:weather:clock" # Default options/items to include in info section of panel.

stepSetup() {
    separateStep
}

bg() {
    gradientGet
}

activebg() {
    colort 20 "$(bg)"
}
