#!/usr/bin/env bash
# base16 ocean theme

# theme
THEME_NAME=ocean
VIM_COLORS=chameleon
BG_COMMAND="feh --bg-fill $HOME/.wm/walls/fill/ocean.jpg"

# use to surround with 'blocks'
p_delimiter="   "

emacs_theme="base16-ocean"

# bspwm
b_border_width=6
b_window_gap=30

# panel
p_padding=3
p_window_class=noshadow
p_height=32
p_gap=0
p_font_main="Droid Sans-10"
p_font_icon="FontAwesome-10"
p_desktop_display_name=name
p_desktop_show_free=false
p_desktop_only_active=true
p_title_only_show_active=false
p_bg_inactive=$p_bg_normal
p_format="dropdown:themeSwitch:desktop:title|mpd|volume:updates:weather:clock"

for item in dropdown themeSwitch desktop title mpd volume updates weather clock;
do
    eval p_${item}_underline=true
    eval p_${item}_overline=true
done


#bg() {
    #colort 30 $p_bg_normal
    #step=$((step+1))
    #eval echo \\\#\$color${step}
#}

border_color="$(colort -50 -t "$p_fg_normal")"
border_width=1

line() {
    #colort -i $(bg)
    echo \#ff$border_color
}

p_line=$border_width
suffix() {
  #border_color="$(colort -t $(bg))"
  echo "%%{B#ff${border_color}}%%{O${border_width}}%%{B-}"
}

prefix() {
  #border_color="$(colort -t $(bg))"
  echo "%%{B#ff${border_color}}%%{O${border_width}}%%{B-}"
}
