#!/usr/bin/env bash

# theme
VIM_COLORS=PaperColor
BG_COMMAND="feh --bg-tile $HOME/.wm/walls/tiled/seigaiha.png"
emacs_theme="base16-grayscale-light"

# bspwm
b_border_width=6
b_window_gap=20
b_normal_border_color=$(colort -20 -t $p_bg_normal)
b_active_border_color=$(colort -40 -t $p_bg_normal)
b_focused_border_color=$(colort -100 -t $p_bg_normal)

p_bg_active="#ff$b_focused_border_color"

theme_section_bg="$(colort -10 $p_bg_normal)"
p_bg_normal="#ff$b_active_border_color"

p_format="dropdown:desktop|title|mpd:volume:weather:clock" # Default options/items to include in info section of panel.

background=$(colort -3 -t $background)

# panel
p_height=24
p_gap=0
p_line=3
p_class="noshadow"

p_padding=1

st_font="Roboto Mono-11"
p_font_main="Roboto Mono-11"
p_font_icon="none"
d_font="Roboto Mono 10"

onlyShowActiveDesktop=true
maxWinNameLen=16

GTK_FONT="Roboto Mono 10"


set_even() {
    #[ $((step%2)) -eq 0 ] && even=true || even=false
    [ $((step%2)) -eq 0 ] && even=false || even=true
}

bg() {
  set_even
  [ $((step%2)) -eq 0 ] && even=false || even=true
  $even && echo "$theme_section_bg" || activebg
}

suffix() {
  set_even
  [ $((step%2)) -eq 0 ] && even=false || even=true
  border="%%{B$(colort +50 $(bg))}%%{O2}%%{B-}"
  $even && echo "" || echo "$border"
}

prefix() {
  set_even
  [ $((step%2)) -eq 0 ] && even=false || even=true
  border="%%{B$(colort +50 $(bg))}%%{O2}%%{B-}"
  $even && echo "" || echo "$border"
}
