#!/bin/sh

# theme
BG_COMMAND="feh --bg-tile $HOME/.wm/walls/tiled/seigaiha.png"
emacs_theme="base16-grayscale-dark"
emacs_powerline_scale="1.0"

# bspwm
b_border_width=1
b_window_gap=30

b_bspwmrc_extend="
radiate &
"

p_desktop_occupied_label='1'
p_desktop_empty_label='0'

st_borderpx=0

p_height=14
p_gap=0
p_line=1
p_window_class="noshadow"
p_line=2
p_padding=6

p_font_main="GohuFont-11"
p_offset=-3
p_font_icon="Siji-10" # Panel Icon font.
p_icon_enable=false
d_font="Go Mono for Powerline 10"

st_font="GohuFont-11"
st_font_variable="GohuFont-11"

l_complete="-"
l_sep="|"

p_title_only_show_active=true

p_format="desktop:org_task"
p_bg_normal="#00$background"

# p_title_theme="fg=\"#ff$(colort -t 30 525252)\""
# p_desktop_theme="fg=\"#ff$(colort -t 30 525252)\""

c_shadow="false"
c_frame_opacity="1.0"
c_shadow_opacity="0.5"
c_shadow_radius="5"
c_shadow_offset_x="-8"
c_shadow_offset_y="-8"

c_fading="false"
c_fade_in_step="0.1"
c_fade_out_step="0.1"

activebg() {
    echo "#00000000"
}

bg() {
    echo "#00000000"
}
