#!/usr/bin/env bash
# spring theme
# based off of my submission to the fist #rice contest 2015.

colors() {
base00="231e18"
base01="302b25"
base02="48413a"
base03="9d8b70"
base04="b4a490"
base05="cabcb1"
base06="d7c8bc"
base07="e4d4c8"
base08="d35c5c"
base09="ca7f32"
base0A="e0ac16"
base0B="b7ba53"
base0C="6eb958"
base0D="88a4d3"
base0E="bb90e2"
base0F="b49368"

foreground=$base05
background=$base00
cursorColor=$base05
color0=$base00
color1=$base08
color2=$base0B
color3=$base0A
color4=$base0D
color5=$base0E
color5=$base0E
color6=$base0C
color7=$base05

color8=$base03
color9=$base09
color10=$base01
color11=$base02
color12=$base04
color13=$base06
color14=$base0F
color15=$base07
}

settings() {

# theme
VIM_COLORS=chameleon
BG_COMMAND="feh --bg-fill $HOME/.wm/walls/fill/spring.jpg"
BG_COMMAND="feh --bg-fill $HOME/Downloads/allan-nygren-293261-unsplash.jpg"
BG_COMMAND="feh --bg-fill $HOME/Downloads/wallhaven-717589.jpg"

emacs_theme="base16-atelier-forest"
st_font="Roboto Mono Medium for Powerline-10"
st_font="Roboto Mono Medium for Powerline-10"

# bspwm
b_border_width=7
b_window_gap=45
b_normal_border_color=$(colort -t +50 $p_bg_inactive)
b_active_border_color=$(colort -tl +60 $p_bg_active)

# panel
p_height=24
p_gap=0
p_line="5"
p_font_main="Droid Sans-10:style=Bold"
p_window_class="noshadow"
p_delimiter="   "
p_line=5
p_desktop_occupied_label="        "
p_desktop_empty_label="        "

maxWinNameLen=50

# colors
p_bg_inactive="#66$(colort -t $p_bg_normal)"
p_bg_normal="#00$(colort -t $p_bg_normal)"

d_font="Droid Sans 10"

# other
GTK_FONT="Droid Sans 10"

# Make the workspaces be in the middle.
p_format="dropdown:title|desktop|mpd:clock"
c_frame_opacity="0.6"
p_icon_handler="env printf \"\$icon_result  \""

activebg() {
    bg
}

activefg() {
    fg
}

p_title_show_mode=active

p_bg_active="$(colort -30 $p_bg_active)"
p_desktop_theme=$(cat<<EOF
bg="#00000000"
activeBG="#00000000"
overline=true
activeoverline=true
line=$p_bg_inactive
activeline=$p_bg_active
line=#99$(colort -t +50 $p_bg_inactive)
delimiter="   "
EOF
)
}
