#!/usr/bin/env bash
# idea: bspwm colors from emacs as well

# test theme
colors() {
    color0=F9F9F9
    color1=D40000
    color2=8FA3AD
    color3=D74214
    color4=7D56C1
    color5=65BA69
    color6=41A4F4
    color7=536D79
    color8=7F7F7F
    color9=D40000
    color10=8FA3AD
    color11=D74214
    color12=7D56C1
    color13=65BA69
    color14=41A4F4
    color15=536D79
    foreground=546E7A
    # background=F7F7F7

    background=FAFAFA
    cursorColor=8B94C6

    color0=FEFEFE
    color1=A70000
    color2=213EBE
    color3=6F3600
    color4=5216AB
    color5=082F5F
    color6=710F44
    color7=000000
    color8=4F4F4F
    color9=A70000
    color10=213EBE
    color11=6F3600
    color12=5216AB
    color13=082F5F
    color14=710F44
    color15=000000
    foreground=000000
    background=FAFAFA
    cursorColor=8B94C6

    # lab light (from the xresources)
    color0=5a5e65
    color8=73777d
    color1=d04245
    color9=ff7f79
    color2=008c36
    color10=30c36e
    color3=897500
    color11=c0a946
    color4=007bd9
    color12=69afff
    color5=ba48b4
    color13=f083e7
    color6=008fac
    color14=00c5e0
    color7=dee2ea
    color15=eef0f3
    background=eef0f3
    foreground=5a5e65
}

settings() {
    # theme
    # BG_COMMAND="feh --bg-tile /home/neeasade/git/neeasade.net/pattern_125.gif"
    BG_COMMAND="${HOME}/.fehbg"

    # emacs_theme="apropospriate-light"
    # emacs_theme="base16-grayscale-light"
    emacs_theme="lab-light"
    emacs_powerline_scale="1.0"
    PROMPT_CHAR='%'
    PROMPT_CHAR='♥'

    # bspwm
    b_border_width=1

    # b_normal_border_color=B0A8A6
    b_normal_border_color=$(colort -t $(lessen 20 $color0))
    b_window_gap=32
    b_window_width=10

    b_bspwmrc_extend="tag_borders &"

    x_padding=6

    # b_normal_border_color=eeeff0
    # b_active_border_color=cecece
    # b_focused_border_color=$(colort -b 20 -t $(lessen 10 $foreground))
    # b_focused_border_color=$(elisp -r '(face-attribute 'font-lock-variable-name-face :foreground)')
    b_focused_border_color=$(colort -t $(elisp -r "(face-attribute 'font-lock-variable-name-face :foreground)"))

    # p_gap=$(elisp '(frame-fringe-width)')
    p_gap=0

    p_bg_middle=$(elisp -r "(ns/color-shorten (face-attribute 'ns/mode-line-middle :background))")
    p_bg_active=$(elisp -r "(ns/color-shorten (face-attribute 'company-tooltip-selection :background))")
    p_fg_active=$foreground

    # elisp -r "(face-attribute 'region :background)"

    # p_bg_middle=$(elisp -r "(face-attribute 'ns/mode-line-inactive :background)")

    # p_fg_active="#ff525252"
    p_format="org_task:title|tags|mpd:weather:clock"
    # p_format="tags:toots:title|org_task|mpd:weather:clock"
    p_format="tags:title:misc:circe_dms|mpd|weather:clock"

    # p_format="battery|desktop|clock"
    # todo: offset should be per font -- it can be in lemonbar
    p_offset="-1"

    p_title_show_mode=active         # used by title.

    p_height=24
    # p_gap=0
    p_window_class="noshadow"
    p_line=2
    # p_padding=6

    # p_font_main="Charter-10:style=Bold"
    p_font_main="Equity Text B-11"
    # p_font_main="Charter-10:style=Bold"
    p_font_icon="FontAwesome-10" # Panel Icon font.
    p_icon_enable=false
    p_desktop_display_name=name
    # d_font="Go Mono for Powerline 14"
    d_font="Equity Text A 12"

    # p_desktop_occupied_label=$(uchar f111)
    # p_desktop_empty_label=$(uchar f1db)

    p_desktop_tiling_label=''
    p_desktop_monocle_label=$(uchar f00b)

    # st_font="Go Mono for Powerline-12:style=Regular"
    st_font="Triplicate T4c-12"
    st_font_variable="Equity Text A-13"
    p_title_only_show_active=true
    maxWinNameLen=40

    p_title_theme="fg=#ff$(colort -t 30 525252)"
    p_desktop_theme="fg=#ff$(colort -t 30 525252)"

    c_shadow="false"
    c_frame_opacity="1.0"
    c_shadow_opacity="0.5"
    c_shadow_radius="5"
    c_shadow_offset_x="-8"
    c_shadow_offset_y="-8"

    c_fading="false";
    c_fade_in_step="0.1"
    c_fade_out_step="0.1"
}

activeline() {
    activefg
}

line() {
    bg
}

bg() {
  # gradient $total $background d7cdff | sed -n ${step}p
  # gradient $total d7cdff $background | sed -n ${step}p

# btags state-plain | awk '{print $3}' | sed -n ${step}p
# return

    cat<<EOF | sed -n ${step}p
#9abcdd
#dae4e5
#697fa3
#97c2c1
#cad8d2
#eae7e3
#69a4a2
#94c0c2
#94c0c2
#69a4a2
#296e6b
#69a4a2
#94c0c2
#dae4e5
$color13
$color4
$color12
$color4
$color5
$color6
$color7
EOF

}

stepSetup() {
    # togetherStep
    separateStep
}

suffix() {
    if [ "$lemon_target_align" = left ]; then
	color=$(elisp -r "(face-attribute 'ns/mode-line-sep :background)")

	if $lemon_target_end; then
	    color=$(elisp -r "(face-attribute 'ns/mode-line-sep-edge :background)")
	fi
	color=$(colort -t "$color")
	# bs O3 B${color}
	bs B00000000 ":   "
    fi

    if [ "$lemon_target_align" = center ]; then
	color=$(elisp -r "(face-attribute 'ns/mode-line-sep :background)")
	color=$(colort -t "$color")
	# bs O3 B${color}
	bs B00000000 ":   "
    fi
}

prefix() {
    if [ "$lemon_target_align" = right ]; then
	color=$(elisp -r "(face-attribute 'ns/mode-line-sep :background)")
	if $lemon_target_end; then
	    color=$(elisp -r "(face-attribute 'ns/mode-line-sep-edge :background)")
	fi

	color=$(colort -t "$color")
	# echo "%{B#FF${color}}%{O3}%{B-}"
	# bs O3 B${color}
	bs B00000000 ":   "
    fi

    if [ "$lemon_target_align" = center ]; then
	color=$(elisp -r "(face-attribute 'ns/mode-line-sep :background)")
	color=$(colort -t "$color")
	# bs O3 B${color}
	bs B00000000 ":   "
    fi
}
