#!/usr/bin/env dash
# base16 twilight theme

colors() {
    background=1e1e1e
    foreground=a7a7a7
    color0=1e1e1e
    color1=cf6a4c
    color2=8f9d6a
    color3=f9ee98
    color4=7587a6
    color5=9b859d
    color6=afc4db
    color7=a7a7a7
    color8=5f5a60
    color9=cf6a4c
    color10=8f9d6a
    color11=f9ee98
    color12=7587a6
    color13=9b859d
    color14=afc4db
    color15=ffffff
    color16=cda869
    color17=9b703f
    color18=323537
    color19=464b50
    color20=838184
    color21=c3c3c3
}

settings() {
    # theme
    VIM_COLORS=chameleon
    BG_COMMAND="feh --bg-fill $HOME/.wm/walls/fill/lake.jpg"

    emacs_theme="base16-twilight"

    c_frame_opacity="0.0"

    # bspwm
    b_border_width=8
    b_window_gap=30
    b_normal_border_color="2e2e2e"

    # panel
    p_height=32
    p_gap=0
    p_line=2
    p_font_main="Droid Sans-10"
    p_font_icon="FontAwesome-10"
    p_padding=12

    p_desktop_show_free=false          # option to show nothing for free desktops.
    p_desktop_display_name=name
    p_desktop_only_active=false       # only show the active desktop name
    p_title_only_show_active=true    # used by title.

    p_icon_handler="env printf \"\$icon_result  \""

    p_format="dropdown:themeSwitch:desktop:title|mpd|volume:updates:weather:clock" # Default options/items to include in info section of panel.

    # colors
    p_bg_inactive="#ff1e1e1e"
    p_bg_active="#ff2d2d2d"
    p_fg_active="$p_fg_normal"
}
