#!/usr/bin/env dash
# zenburn theme

colors() {
    background=3f3f3f
    foreground=dcdccc
    color0=3f3f3f
    color10=c5f779
    color11=fff796
    color12=4186be
    color13=cf9ebe
    color14=71bebe
    color15=ffffff
    color1=9e1828
    color2=aece92
    color3=968a38
    color4=616191
    color5=963c59
    color6=418179
    color7=bebebe
    color8=666666
    color9=cf6171
}

settings() {
    # theme
    BG_COMMAND="feh --bg-fill $HOME/.wm/walls/fill/desert.png"
    emacs_theme=base16-zenburn
    emacs_powerline_scale="1"

    # bspwm
    b_border_width=4
    b_window_gap=12

    # panel
    p_height=28
    p_font_main="terminus-8"
    p_font_icon="siji-8"
    p_gap=2

    desktopdisplay=name
    nomodetoggle=true
    # sneak an extra launch parameter onto lemonbar to show no shadows.
    p_underline="4"
    p_window_class="noshadow"

    # colors
    p_bg_normal="#003f3f3f"
    p_bg_inactive="#ff3f3f3f"
    p_padding=2
    # p_icon="$(colort 40 "$pBG")"

    # Workspace variables
    DT='[-]'
    DM='[]'

    # other
    d_font="Terminess Powerline-8"
    GTK_FONT="Terminess Powerline-8"
    st_font="Terminess Powerline-12"
    st_borderpx=2

}
