#!/bin/sh
# depends on git, sh.

for dir in bin git notes .config; do
  mkdir -p "$HOME/$dir"
done

[ ! -d "$HOME/.dotfiles" ] && git clone "https://github.com/neeasade/dotfiles" "$HOME/.dotfiles"
cd "$HOME/.dotfiles"

echo >/tmp/stow_conflicts
stoww() {
    # this is only for situations where you don't have stow
    "${HOME}/.dotfiles/bin/bin/stowo" "$@" 2>/tmp/stow_conflicts
}

core() {
  stoww bin shell vim tools qutebrowser
}

emacs() {
  git clone "https://github.com/neeasade/emacs.d" "$HOME/.emacs.d"

  # initial launch/install packages
  type emacs >/dev/null 2>&1 && emacs --debug-init
}

rice() {
  core
  stoww sxhkd wm
}

windows() {
  # prereq: windows/bootstrap.cmd
  core

  for item in "$(cat $HOME/.dotfiles/windows/scoop.txt)"; do
    scoop install $item
  done

  # windows bin
  stoww windows
}

if [ -z "$*" ]; then
    echo "options: core, rice, emacs"
    exit 1
fi

# core, emacs, rice, windows
echo bootstrapping ${1}...
$1
cat /tmp/stow_conflicts | grep conflict
echo bootstrapped ${1}...
