#!/bin/sh
. profile

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT
CUR_X_OFFSET=0
num_mon=$(bspc query -M)
for i in $num_mon; do
    [ -e "$PANEL_FIFO$i" ] && rm "$PANEL_FIFO$i"
    mkfifo "$PANEL_FIFO$i"

    #|  grep -o "[Mm]$1[^mM]*T"
    bspc control --subscribe > "$PANEL_FIFO$i" &
    xtitle -t 80 -sf 'T%s' > "$PANEL_FIFO$i" &

    date "+S%H:%M " > "$PANEL_FIFO$i" &

    CUR_MON_WIDTH=$(bspc query -T -m $i | grep -oE "[0-9]{2,6}" | head -n 1)

    . panel_colors
    cat "$PANEL_FIFO$i" | panel_bar | bar -g $(expr $CUR_MON_WIDTH - $(expr $PANEL_GAP + $PANEL_GAP))x$PANEL_HEIGHT+$(expr $CUR_X_OFFSET + $PANEL_GAP)+$PANEL_GAP -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" | sh &
    CUR_X_OFFSET=$(expr $CUR_X_OFFSET + $CUR_MON_WIDTH )
done

wait

