#!/bin/sh
. profile

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT


num_mon=$(bspc query -M)
for i in $num_mon; do
    [ -e "$PANEL_FIFO$i" ] && rm "$PANEL_FIFO$i"
    mkfifo "$PANEL_FIFO$i"

    #|  grep -o "[Mm]$1[^mM]*T"
    bspc control --subscribe > "$PANEL_FIFO$i" &
    xtitle -t 80 -sf 'T%s' > "$PANEL_FIFO$i" &

    date "+S%H:%M " > "$PANEL_FIFO$i" &

    . panel_colors
    cat "$PANEL_FIFO$i" | panel_bar | bar -g 1350x$PANEL_HEIGHT+8+8 -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" | sh &
done

wait


GetBSPWMMonWidth()
{
    
}
