#!/bin/sh

. panel_colors

num_mon=$(bspc query -M | wc -l)

CBR='%{B-}'         # reset bg color
CB1='%{B#FF66D9EF}' # blue
CB2='%{B#FF292929}' # off white

CFR='%{F#FFFFFFFF}'         # reset fg color
CF1='%{F#FF49483E}' # dark gray
CF2='%{F#FFFFFFFF}' # blue
CF3='%{F#FFF92672}' # violet
CF4='%{F#FF777777}' # off white

RA='%{r}'           # right align
AC='%{A:'           # start click area
AB=':}'             # end click area cmd
AE='%{A}'           # end click area

LT='t'              # tiled layout
LM="f"              # monocle layout

DO='O'              # occupied desktop
DF='X'              # free desktop

goto='bspc desktop -f'       # go to this desktop
cycle='bspc desktop -l next' # cycle tiled/monocle

while read -r line ; do
	case $line in
	S*)
		sys_infos="${RA}${line#?}"
	;;
	T*)
		title="${CFR} ${line#?} "
	;;
	W*)
		wm_infos="${CB2}"
		IFS=':'
		set -- ${line#?}
		while [ $# -gt 0 ] ; do
			item=$1
			name=${item#?}
			case $item in
			O*) wm_infos="${wm_infos}${CF2}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # active occupied desktop
			F*) wm_infos="${wm_infos}${CF2}${AC}${goto} ${name}${AB} ${DF} ${AE}";; # active free desktop
			U*) wm_infos="${wm_infos}${CF3}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # active urgent desktop
			o*) wm_infos="${wm_infos}${CF1}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # inactive occupied desktop
			f*) wm_infos="${wm_infos}${CF1}${AC}${goto} ${name}${AB} ${DF} ${AE}";; # inactive free desktop
			u*) wm_infos="${wm_infos}${CF3}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # inactive urgent desktop
			L*)
				# layout
				case $name in
				t*) # tiled
					layout=${LT}
				;;
				m*) # monocle
					layout=${LM}
				;;
				esac
				wm_infos="${wm_infos} ${CF1}${AC}${cycle}${AB}${layout}${AE} ${CBR}${CF4}"
			;;
			esac
			shift
		done
	;;
	esac
    printf "%s\n" "%{l}$wm_infos %{c}$title %{r}$sys_infos"
done
