#!/bin/sh
. profile

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT


num_mon=$(bspc query -M)
#export PANEL_FONT_FAMILY=termsyn
for i in $num_mon; do
    [ -e "$PANEL_FIFO$i" ] && rm "$PANEL_FIFO$i"
    mkfifo "$PANEL_FIFO$i"

    #|  grep -o "[Mm]$1[^mM]*T"
    bspc control --subscribe > "$PANEL_FIFO$i" &
    xtitle -sf 'T%s' > "$PANEL_FIFO$i" &

    echo S$'\342\256\227' > "$PANEL_FIFO$i" &
    #date +S%H:%M > "$PANEL_FIFO$i" &

    . panel_colors
    cat "$PANEL_FIFO$i" | panel_bar | bar -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" %{S%i} | sh &
done

wait
