#!/bin/sh

bspc config border_width        3
bspc config window_gap         12
bspc config top_padding        32

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_m3onocle     true
bspc config focus_by_distance   true

#bspc monitor "DisplayPort-0" -n 1 -d I II III
#bspc monitor "HDMI-0" -n 2 -d IV V VI
#bspc monitor "DVI-1" -n 3 -d VII VIII IX X

desktops=$(bspc query -M)

#host specific(to maintain monitor order.)

if [ "$HOSTNAME"=='home27' ]; then
    desktops="HDMI-0 DisplayPort-0 DVI-1";
fi
    
i=1
for monitor in $desktops; do
    bspc monitor "$monitor" \
        -n "$i" \
        -d $i/{i,ii,iii,iiii,iiiii}
    let i++
done

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
#bspc config normal_border_color "#332d29"
bspc config active_border_color "#AAAAAA"
bspc config focused_border_color "#FFFFFF"
#bspc config presel_border_color "#9a875f"
#bspc config urgent_border_color "#9f7155"
#bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1


bspc rule -a mplayer2 floating=on
bspc rule -a VLC desktop=^7 
bspc rule -a Screenkey manage=off

~/.config/bar/panel &
