#!/bin/sh

#Enable/disable gaps on both windows and bar
export BSPWM_GAPS=true

#Get panel height
. ~/.config/bar/profile


#GAP specific options
if [ "$BSPWM_GAPS" = true ]; then
    bspc config window_gap         12
    bspc config top_padding        $(expr $PANEL_HEIGHT + $PANEL_GAP)
    bspc config borderless_monocle false
    bspc config gapless_monocle    false
else
    bspc config window_gap         0
    bspc config top_padding        $PANEL_HEIGHT
    bspc config borderless_monocle  true
    bspc config gapless_monocle     true
fi
# Visual options
#THICK BORDERS FOR LYFE
bspc config border_width        3
bspc config split_ratio         0.50
bspc config focus_follows_pointer true
bspc config focus_follows_monitor true
bspc config auto_alternate true
bspc config auto_cancel true
#bspc config normal_border_color "#332d29"
bspc config active_border_color "#AAAAAA"
bspc config focused_border_color "#FFFFFF"
#bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#FFFF00"
#bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

. desktops
