#!/usr/bin/env bash

# regen i3blocks config:
# theme refresh lemonade

bspc config top_padding $(theme getval p_height)

geom=$(
    eval "$(theme get)"
    dim() {
	bspc query -T -m | jq .rectangle.$1
    }

    gapped=$(iif "[ ! $(bspc config window_gap) -le 0 ]")
    p_gap=$(iif $gapped $p_gap 0)
    top=$(iif "[ "$p_position" = "top" ]")
    echo "$(( $(dim width)-(p_gap*2) ))x$p_height+$(( $(dim x)+p_gap ))+$(iif $top $p_gap $(($(dim height)-(p_gap+p_height))) )"
)

# eg desktop:circe_dms:title|org_task|mpd:volume:clock
# -> $desktop $circe_dms $title %{c}$org_task %{r}mpd $volume $clock
p_format=$(theme getval p_format)
# p_format='org_task:title|none|mpd:weather:clock'
# p_format='tags:title|org_task|mpd:weather:clock'

format=$(echo "$p_format" | sed 's/:/$/g' | sed 's/|/%{c}$/' | sed 's/|/%{r}$/' )
format="\$$format"

# 	echo lemonbar -d \
# -u $(theme getval p_line) \
# -n $(theme getval p_window_class) \
# -B \#cceef0f3 \
# -F \#ff5a5e65 \
# -o -1 \
# -f 'Equity Caps B-10:style=Regular' \
# -f 'Equity Caps B-10:style=Bold' \
# -f 'Equity B-10' \
# -a 40 \
# -g "$(get_geometry)"


# stdbuf -oL all the things.
# this has been poked at alot by a tired me, I think it's good now.
echo what
stdbuf -oL i3blocks -o j | \
    stdbuf -oL sed 's/\},/}\n,/g' | \
    stdbuf -oL sed -e 's/^,//' -e 's/\[//' -e 's/\]$//' | \
    stdbuf -oL grep '^{' | \
    stdbuf -oL jq -r '.name + " " + .full_text' | \
    stdbuf -oL sed "s#'#\'\\\'\'#g" | \
    while IFS=$'\n' read -r event; do
	eval "${event%% *}=\${event#* }"
	eval "echo \"$format\""
    done | stdbuf -oL debounce.js 30 | \
	lemonbar -d \
-u $(theme getval p_line) \
-n $(theme getval p_window_class) \
-B \#cceef0f3 \
-F \#ff5a5e65 \
-o -1 \
-f 'Equity Caps B-10:style=Regular' \
-f 'Equity Caps B-10:style=Bold' \
-f 'Equity B-10' \
-a 20 \
-g "$geom"

