#!/usr/bin/env bash

mpc idleloop | while read -r line; do
    if [ "$line" = "player" ]; then
	state=$(mpc)
	if grep -i 'club life' <<< "$state"; then
	    if grep '0:00' <<< "$state"; then
		# skip intro
		mpc seek +25
	    fi
	fi
    fi
done
