#!/bin/sh

.  "$HOME/.sh.d/environment"

inotifywait -m "${HOME}/Downloads" -e create -e moved_to | debounce.js 30 | \
    while read dir action file; do
	vdo rm "${HOME}/Last_Shot/last_download_"*
	vdo ln -s "${dir}/${file}" "${HOME}/Last_Shot/last_download_${file}"
    done
