#!/usr/bin/env bash


sound_options() {
  # echo foo
  while read -r option; do
      desc=$(cut -d, -f1 <<< "$option")
      printf ",%s,%s\n" "$desc" "$(cut -d, -f2 <<< "$option")"
      # add_switch "meta: sound switch $(cut -d, -f1 <<< "$option")" "$(cut -d, -f2 <<< "$option")"
  done <<< $(paste -d, <(pacmd list-sinks | grep device.description | awk -F= '{print $2}' | sed 's/"//g') \
		   <(pactl list short sinks | awk '{print "pa-move-sinks " $1}'))
}

pick() {
  cat<<EOF | sed 's/,/\t/g' | pmenu
fun
,discord,discord
,telegram,find_url web.telegram.org
,twitter,find_url twitter.com
sound
,pavucontrol,find_pavucontrol
$(sound_options)
UI
,panel,panelt
,layout
,,tiled,fullscreen_toggle.sh do_tiled
,,focus,fullscreen_toggle.sh do_monocle_slim
,,full,fullscreen_toggle.sh do_monocle_full
,,gaps,gapt
,stalonetray,bash -ic 'stalonetray'
Music
,toggle,player.sh toggle
EOF
}

# add screenshots

systemctl --user stop unclutter
# pick

a=$(pick)
PMENU=t
. "$(which dmenu_switcher)"
add_metas >/dev/null
add_tags >/dev/null
eval "$a"
systemctl --user start unclutter
