#!/usr/bin/env dash
# eval things, handle special cases.

# the prefix used to signal upper panel:
prefix=meta

case "$*" in
  invert)
    eval echo ${prefix}${juicedLemon}_background="\$${juicedLemon}_foreground"
    eval echo ${prefix}${juicedLemon}_foreground="\$${juicedLemon}_background"
    ;;
  active)
    eval echo ${prefix}${juicedLemon}_background="\$${juicedLemon}_activebg"
    eval echo ${prefix}${juicedLemon}_foreground="\$${juicedLemon}_activefg"
    ;;
  reset)
    eval echo ${prefix}${juicedLemon}_background="\$${juicedLemon}_background"
    eval echo ${prefix}${juicedLemon}_foreground="\$${juicedLemon}_foreground"
    ;;
  start)
    echo ${prefix}start
    ;;
  end)
    echo ${prefix}end
    ;;
  set*)
    # assume "set <content>", eg "set foreground=#ffffff"
    shift
    echo "${prefix}${juicedLemon}_$*"
    ;;
  *)
    echo "${prefix}$*" ;;
esac
