#!/bin/sh
# usage: mkb <percent> <size>
# port of http://git.z3bra.org/mkb/file/mkb.c.html

# args
progress=${1:-0}
size=$2

complete='-'
empty='-'
sep='+'
start=''
end=''

eval "$(theme -n mkb -o shell)"

# char width for emoji
# size=$((size / 2))

# defaults
progress=${progress:-30}
size=${size:-32}

passed=false
content=${start}

if [ "$progress" -eq 100 ]; then
    sep=$complete
fi

content="${content}${start}"
for i in $(seq 1 "$size"); do
    if [ "$(echo "$i < $progress / 100 * $size" | bc -l)" = 1 ]; then
        current="$complete"
    else
        $passed && current="$empty" || current="$sep"
        passed=true
    fi

    content="${content}${current}"
done
content="${content}${end}"
echo "$content"
