#!/bin/sh
# usage: mkb ${percent}
# port of http://git.z3bra.org/mkb/file/mkb.c.html
# TODO: consider tying in the options here into themes.

# args
progress="$1"
size="$2"

eval "$(theme get)"

# defaults
progress=${progress:-30}
size=${size:-32}

# some ideas

passed=false
content="${l_start}"

content="${content}${start}"
for i in $(seq 1 $size); do
    if [ "$(echo "$i < $progress / 100 * $size" | bc -l)" = 1 ]; then
        current="$l_complete"
    else
        $passed && current="$l_empty" || current="$l_sep"
        passed=true
    fi
    content="${content}${current}"
done
content="${content}${l_end}"
echo "$content"
