#!/bin/sh

pBG="%{B$pBG}"         # reset bg color
pFG="%{F$pFG}"         # reset fg color


pBGS1="%{B$pS1}"  # bg shade 1
pBGS2="%{B$pS2}"  # bg shade 2

pFGS1="%{F$pS1}"  # fg shade 1
pFGS2="%{F$pS2}"  # fg shade 2


RA='%{r}'           # right align
AC='%{A:'           # start click area
AB=':}'             # end click area cmd
AE='%{A}'           # end click area

DO='▪'              # occupied desktop
DF='▫'              # free desktop

goto='bspc desktop -f'       # go to this desktop
cycle='bspc desktop -l next' # cycle tiled/monocle
winfocus='bspc window -f '    #focus on a window

while read -r line ; do
	case $line in
	S*)
		sys_infos="${line#?}"
	;;
	T*)
        title="%{F$pRest}"
		IFS='>>'
        set -- ${line#?}
		while [ $# -gt 0 ] ; do
            item=$1
            name=${item#?}
            winTitle="$(echo $name | grep -oE ".*//" | rev | cut -c 3- | rev)"
            winID="$(echo $name | grep -oE "//.*" | cut -c 3-)"
            #form of $name will be window title // window id.
            #split and use for clickable focus areas
            if [ ! -z "$winTitle" ]; then
                case $item in
                A*) title="${title}%{F$pActive}${pBGS2}%{E5}     ${winTitle} ${AE}%{d5}     ${pBG}%{F$pRest}";; #active window
                X*) title="${title}${AC}${winfocus} ${winID}${AB} ${winTitle} ${AE}";; #inactive window in monocle
                esac
            fi;
            shift
        done
	;;
	W*)
		wm_infos="${pBGS2}"
		IFS=':'
		set -- ${line#?}
		while [ $# -gt 0 ] ; do
			item=$1
			name=${item#?}
			case $item in
			O*) wm_infos="${wm_infos}%{F$pActive}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # active occupied desktop
			F*) wm_infos="${wm_infos}%{F$pActive}${AC}${goto} ${name}${AB} ${DF} ${AE}";; # active free desktop
			U*) wm_infos="${wm_infos}%{F$pUrgent}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # active urgent desktop
			o*) wm_infos="${wm_infos}%{F$pRest}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # inactive occupied desktop
			f*) wm_infos="${wm_infos}%{F$pRest}${AC}${goto} ${name}${AB} ${DF} ${AE}";; # inactive free desktop
			u*) wm_infos="${wm_infos}%{F$pUrgent}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # inactive urgent desktop
			esac
			shift
		done
        #wm_infos="$wm_infos${pBG} "
        wm_infos="$wm_infos%{d5}     ${pBG} "
	;;
	esac
    printf "%s\n" "%{r}$sys_infos %{l}$wm_infos$title"
done
