#!/bin/sh

CBR='%{B-}'         # reset bg color
CB1='%{B#FF66D9EF}' # blue
CB2='%{B#FF505050}'

CFR='%{F#FFFFFFFF}'         # reset fg color
CF1='%{F#FFa2a2a2}' # dark gray
CF2='%{F#FFFFFFFF}' # white
CF3='%{F#FFFFFF00}' # yello
CF4='%{F#FF505050}' # off white

RA='%{r}'           # right align
AC='%{A:'           # start click area
AB=':}'             # end click area cmd
AE='%{A}'           # end click area

LT='t'              # tiled layout
LM="f"              # monocle layout

DO='■'              # occupied desktop
DF='□'              # free desktop

goto='bspc desktop -f'       # go to this desktop
cycle='bspc desktop -l next' # cycle tiled/monocle

while read -r line ; do
	case $line in
	S*)
		sys_infos="${RA}${line#?}"
	;;
	T*)
		title="${CF4}${CB2}${CFR} ${line#?} ${CF4}${CBR}⮀"
	;;
	W*)
		wm_infos="${CB2}"
		IFS=':'
		set -- ${line#?}
		while [ $# -gt 0 ] ; do
			item=$1
			name=${item#?}
			case $item in
			O*) wm_infos="${wm_infos}${CF2}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # active occupied desktop
			F*) wm_infos="${wm_infos}${CF2}${AC}${goto} ${name}${AB} ${DF} ${AE}";; # active free desktop
			U*) wm_infos="${wm_infos}${CF3}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # active urgent desktop
			o*) wm_infos="${wm_infos}${CF1}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # inactive occupied desktop
			f*) wm_infos="${wm_infos}${CF1}${AC}${goto} ${name}${AB} ${DF} ${AE}";; # inactive free desktop
			u*) wm_infos="${wm_infos}${CF3}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # inactive urgent desktop
			L*)
			;;
			esac
			shift
		done
	;;
	esac
    printf "%s\n" " %{c}$title %{r}$sys_infos %{l}$wm_infos${CBR}%{F#FF505050}⮀${CF4}"
done
