#!/bin/sh
# profile
# Set values to be referenced in other bar scripts.

# get the value of a color from the current xrdb load configuration
getXresColor() {
    echo -n "$( xrdb -query | grep  "\*.$1:" | grep -oE "#[a-zA-Z0-9]{6}" | cut -c 2- )";
}

# Panel display settings
PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=22
PANEL_FONT_FAMILY="Dejavu Sans-8,FontAwesome-8"
PANEL_GAP=6
# Spacing used to separate information on the bar. Can serve as slant angle if using bar slant fork(github.com/neeasade/bar)
pSLANT=3

# Panel colors
pBGS1="%{B#ff$(getXresColor color0)}"   # Alternating bg color 1
pBGS2="%{B#ff$(getXresColor color0)}"   # Alternating bg color 2
pFG="%{F#ff$(getXresColor foreground)}" # Default foreground
pBG=$pBGS1                              # Default background
pTAB=$pBG                               # Unfocused title tab background
cIcon="%{F$pRest}"                      # Color of icons next to system information
cContent="%{F#ffbbbbbb}"                # Color of content next to information icons

# Workspace colors
pUrgent=#ffffff00
pActive=#ff$(getXresColor color15)
pRest=#ff$(getXresColor color6)

# Workspace variables
DO=$(echo -e '\uf135')  # occupied desktop
DF=$(echo -e '\uf005')  # free desktop
DT=$(echo -e '\uf009')  # tiling mode
DM=$(echo -e '\uf0c9')  # monocle mode

# options: mail yaourtUpdates mpd battery network volume weather clock
# If empty, all are used.
# it is possible to specify different information per monitor with barInfo<mon #>="options"
barInfo=""


# Customize options on different computers by hostname:
if [ "$HOSTNAME" = "home27" ]; then
    barInfo1="mpd "
    barInfo2="volume weather mail yaourtUpdates"
    barInfo3="network clock"
fi

[ "$HOSTNAME" = "home2" ] && barInfo="battery network volume clock"

# Export variables and set gap if needed
[ "$BSPWM_GAPS" = false ] && PANEL_GAP=0
export PANEL_FIFO PANEL_HEIGHT PANEL_FONT_FAMILY PANEL_GAP
export pBGS1 pBGS2 pFG pBG pTAB pSLANT cIcon cContent
export pUrgent pActive pRest
export DO DF DT DM
export barInfo
