#!/usr/bin/env bash
# neeasade's bspwmrc
# may take one bool arg: gaps or ungapped

set -a

# if none set, keep whatever is open.
gapped=$1
[ -z "$gapped" ] && gapped=$(iif "! [ $(bspc config window_gap) -le 0 ]")

xinit=$(iif "[ $(( $(date +%s) - xstart )) -lt 2 ]")

PATH=$PATH:$HOME/.wm/scripts/visual

relaunch_panel=$(iif "systemctl --user status panel")

bspc config border_width 1
bspc config split_ratio  0.5

bspc config normal_border_color   "#D0D8E4"
bspc config active_border_color   "#898A8D"
bspc config focused_border_color  "#BC17AB"
bspc config presel_feedback_color "#898A8D"

bspc config focus_follows_pointer     true
bspc config ignore_ewmh_focus         true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors  true
bspc config merge_overlapping_monitors  true

bspc config pointer_modifier mod4
bspc config removal_adjustment false

# external rules
bspc config external_rules_command "$(which external_rules.sh)"

# to gap or not to gap
bspc config window_gap $(iif $gapped 32 -1)

side_padding=$(iif $gapped 0 1)
panel_padding=$(iif $relaunch_panel "24+0" 0)

bspc config top_padding $((side_padding + panel_padding))

for side in right bottom left; do
    bspc config ${side}_padding $side_padding
done

# bspc config borderless_monocle $(iif "! $gapped")
bspc config borderless_monocle true
bspc config single_monocle true

# multihead option is the custom_monocle script
mon_width=$(bspc query -T -m | jq .rectangle.width)
window_width=$(echo .54 \* $mon_width | bc -l)
monocle_pad_width=$(echo "($mon_width - $window_width)/2" | bc -l)
bspc config left_monocle_padding $monocle_pad_width
bspc config right_monocle_padding $monocle_pad_width

# declare desktops per monitor
for monitor in $(bspc query -M); do
    bspc monitor $monitor -d 00 01 10 11
done

if $relaunch_panel; then
    systemctl --user restart panel
fi

for visual in $HOME/.wm/scripts/visual/*; do
    pkill -f "$visual" 2>/dev/null
done

# extensions may be defined in themes here:
tag_borders &

bspc rule -a Emacs state=tiled
bspc rule -a Emacs-27.0.91 state=tiled
bspc rule -a Emacs-27.1 state=tiled

# initial wm startup actions
if $xinit; then
    $HOME/.wm/startup.sh &
    panelt
fi
