#!/bin/sh

icon battery

BATC=/sys/class/power_supply/BAT0/capacity
BATS=/sys/class/power_supply/BAT0/status

charge=100
status=Charging

if [ -f $BATC ]; then
    charge=$(cat $BATC)
fi

if [ -f $BATS ]; then
    status=$(cat $BATS)
fi

# printf '%s%s\n' $(iif "[ '$status' = 'Charging' ]" \+ \-) $charge
printf '%s%s\n' $(iif "[ '$status' = 'Charging' ]" \+ '') "$(mkb $charge 20)"
