#!/usr/bin/env dash
# counter test to ensure sleep reload is working correctly.

target=/tmp/counter
[ ! -e $target ] && echo 0 > $target

counter=$(cat $target)
counter=$(( counter + 1 ))
echo $counter > $target
echo $counter
