#!/bin/sh

eval "$(date +'today=%F now=%s')"
midnight=$(date -d "$today 0" +%s)

percent=$(echo "($((now - midnight)) / 86400 * 100)"  | bc -l | sed 's/\..*//')

"$HOME/.wm/panel/tools/mkb" $percent 24
# printf "%s %s %s\n" \
#        past \
#        $("$HOME/.wm/panel/tools/mkb" $percent 24) \
#        future
