#!/bin/sh
# FUCK. TIME.

. $HOME/.sh.d/environment

eval "$(date +'today=%F now=%s')"
start=7 end=23

if $MAC; then
    # work
    start=8 end=16
fi

start_time=$(date -d "$today $start" +%s)
end_time=$(date -d "$today $end" +%s)

passed=$((now - start_time))
duration=$((end_time - start_time))

percent=$(echo "($passed / $duration * 100)"  | bc -l | sed 's/\..*//')
mkb $percent $((end - start))
