#!/bin/sh
# scrolling mpd text
# limitation of this is it only works with monospace fonts.
# lemonbar support arbitrary stuff

yeah() {
title=$($HOME/.wm/panel/lemons/mpd | tr '[:upper:]' '[:lower:]')
# title=$($HOME/.wm/panel/lemons/mpd)
max_length=$(echo "$title" | cut -c 1-$max_length | wc -L)

# $p_font_main will come from lemonade env
font_name=$(echo $p_font_main | sed 's/-.*//')
font_size=$(echo $p_font_main | sed 's/.*-//')

if [  "$title" = "Stopped" ]; then
    icon music
    echo Stopped
else
    [ -z "$title" ] && exit

    # approach:
    # trim, peek at width with txtw
    # pad with lemonbar width

    # width=$(txtw -f "$font_name" -s $font_size a)

    WIDTH=30
    percent=$(mpc | grep -oE "([0-9]+)%"  | tr -d \%)
    first=$(echo ".$percent * $WIDTH" | bc -l  | sed 's/\..*//')
    second=$((WIDTH - first))

    # end=$(bs 'A1player.sh toggle; pkill -SIGRTMIN+10 i3blocks' ":$title ")
    end="$(bs "B$(colort -70 "$bg")" O${first} +o)$(bs Beef0f3 +o O${second})"

    echo "$title" | skroll -r -n $((max_length-1)) -d 0.2 | stdbuf -oL tail -n +2 | \
	while IFS='\n' read -r out; do
	    if [ "${#out}" -gt 3 ]; then
		printf "%-$((max_length-1))s\n" "$(icon $(iif 'mpc | grep -q playing' pause play))$(bs 'A1mpc toggle' ":$out")$end" | sed 's/ /  /g' | season
	    fi
	done
fi
}

while true; do
    yeah
done
