#!/usr/bin/env dash
# scrolling mpd text

max_length=30

# target is picked based on which might be playing.
mpc | grep -q playing && mpcplaying=true || mpcplaying=false
mpvc | grep -q playing && mpvcplaying=true || mpvcplaying=false

if ! $mpvcplaying && ! $mpcplaying; then
  mpvc >/dev/null && target='mpvc' || target='mpc'
else
  $mpvcplaying && target='mpvc'
  $mpcplaying && target='mpc'
fi

$target | grep -q playing && icon_target=pause
$target | grep -q paused && icon_target=play

if $playing || $paused; then
    title="$($target -f "%title% - %artist%" | head -n 1)"
    # if title is empty, try file and trim from last / if exists.
    if [ "$title" = " - " ]; then
        # https://github.com/wildefyr/mpvc/issues/29
        if [ "$target" = "mpvc" ]; then
            title="$($target -f "%filename%" | head -n 1 | sed 's/.*\///;')"
        else
            title="$($target -f "%file%" | head -n 1 | sed 's/.*\///')"
        fi

        # peel some stuff
        title="$(echo "$title" | sed 's/【.*】//' | sed 's/\.[^.]*$//')"
    fi
else
  title="Stopped"
fi

# set $1 length to $max_length chars (trim or pad)
pad() {
    count=$(echo -n "$1" | wc -m)
    remain=$(( $max_length - $count ))

    padding=""
    if [ $(( $remain % 2 )) -ne 0 ]; then
        remain=$(( $remain - 1 ))
        padding=" "
    fi

    for i in $(seq $remain); do
        padding="$padding "
    done

    echo "$1$padding";
}


max_length=$(echo "$title" | cut -c 1-$max_length | wc -m)
if [  "$title" = "Stopped" ]; then
    icon music
    echo Stopped
else
    echo "$title" | skroll -r -n $((max_length-1)) -d 0 | head -n -1 | \
    while IFS='\n' read -r out; do
        icon music
        icon $icon_target
        pad "$out"
        sleep 0.2
    done 
fi
