#!/bin/sh
# MIT Copyright (c) 2018 Luiz de Milon (kori)
# get current memory usage

t=$(grep MemTotal /proc/meminfo | awk '{print $2}')
f=$(grep MemFree  /proc/meminfo | awk '{print $2}')
b=$(grep ^Buffers /proc/meminfo | awk '{print $2}')
c=$(grep ^Cached  /proc/meminfo | awk '{print $2}')

echo -n $(echo "($t - $f - $c - $b) / 1000" | bc)
