#!/bin/sh
# MIT Copyright (c) 2018 Luiz de Milon (kori)
# get current memory usage

t=$(awk '/MemTotal/{print $2}' /proc/meminfo)
f=$(awk '/MemFree/{print $2}'  /proc/meminfo)
b=$(awk '/^Buffers/{print $2}' /proc/meminfo)
c=$(awk '/^Cached/{print $2}'  /proc/meminfo)

echo $(echo "($t - $f - $c - $b) / 1000" | bc)
