#!/usr/bin/env bash
# this lemon is meant to have temporary things that may popup, show front and center

check_disk_space() {
    # 10G
    # arbitrary
    concern=$((1000 * 1000 * 10))

    df | grep \^/dev | awk '{printf "%s", $4; $1=$2=$3=$4=$5=""; print $0}' | \
	while read avail name; do
	    if [ "$name" = "/boot" ]; then
		continue
	    fi

	    if [ $avail -lt $concern ]; then
		# echo "$avail $name"
		echo "DISK LOW ($name)"
	    fi
	done
}

(
    if ! elisp -q '(eq org-pomodoro-state :pomodoro)'; then
	# this takes awhile b/c batch (~3 secs)
	elisp -br "(ns/conf-core) (ns/make-lines (-filter 'stringp (list (ns/org-status-outdated) (ns/org-status-scheduled))))"
	# echo
    fi

    elisp -r '(when-let (unread-dms (ns/circe-unread-query-buffers))
	(format "DMs: %s" (length unread-dms)))'

    check_disk_space

    if pgrep obs >/dev/null; then
	echo "OBS OPEN"
    fi

    # cache_output 30 elisp -r '(- ns/org-casual-timelimit (ns/with-notes (ns/org-check-casual-time-today)))'
) | awk NF | tr '\n' '^' | sed 's/.$//' | sed 's/\^/ • /g'
echo

