#!/bin/sh

(
    cache_output 500 elisp -r '(ns/export-scheduled-org-headings-past)'

    if pgrep obs >/dev/null; then
	echo "OBS OPEN"
    fi

    cache_output 30 elisp -r '(- ns/org-casual-timelimit (ns/with-notes (ns/org-check-casual-time-today)))'

) | awk NF | tr '\n' '^' | sed 's/.$//' | sed 's/\^/ • /g'
echo

