#!/usr/bin/env dash
# mpd
# planned: left click is toggle pause, right click is next, scroll is mpd volume.

icon $iconfont music

cur_song="$(basename "$(mpc current -f "%artist% - %title%")" | cut -c1-30 )"
if [ -z "$cur_song" ]; then
	echo "Stopped"
else
	paused=$(mpc | grep paused)

	[ -z "$paused" ] && toggle="${AC}mpc pause${AB}$(icon $iconfont pause)${AE}" ||
						toggle="${AC}mpc play${AB}$(icon $iconfont play)${AE}"

	# TODO: define AC,B,E for these to work inline.
	prev="${AC}mpc prev${AB}$(icon $iconfont prev)${AE}"
	next="${AC}mpc next${AB}$(icon $iconfont next)${AE}"
	cur_song="${AC}dzen.sh mpd${AB} $cur_song ${AE}"
	echo "$cur_song $prev $toggle $next"
fi
