#!/usr/bin/env dash
# player by player.sh
# planned: left click is toggle pause, right click is next, scroll is mpd volume.
# todo: consider trimming file extentions

maxWinNameLen=${maxWinNameLen:-30}

player.sh | grep -qi playing && playing=true || playing=false
player.sh | grep -qi paused && paused=true || paused=false

if $playing || $paused; then
    title=$(player.sh -f "%title% - %artist%" | head -n 1)
    # if title is empty, try file and trim from last / if exists.
    if [ "$title" = " - " ]; then
        title=$(player.sh -f "%file%" | head -n 1 | sed 's/.*\///')

        # peel some stuff
        title=$(echo "$title" | sed 's/【.*】//')
    fi
else
  title="Stopped"
fi


# $playing && icon pause
# $paused && icon play

title=$(echo "$title" | cut -c 1-$maxWinNameLen)
echo "$title"

# WIDTH=30
# percent=$(mpc | grep -oE "([0-9]+)%"  | tr -d \%)
# first=$(echo ".$percent * $WIDTH" | bc -l  | sed 's/\..*//')
# second=$((WIDTH - first))

# echo $(bs 'A1player.sh toggle; pkill -SIGRTMIN+10 i3blocks' ":$title $(bs "B$(colort -70 "$bg")" O${first} +o)$(bs Beef0f3 +o O${second})")
