#!/bin/sh
# player by player.sh
# planned: left click is toggle pause, right click is next, scroll is mpd volume.


# playerctl --follow status | while read -r line; do

title=$(playerctl -p mpd status)
if [ "$title" = "Playing" ]; then
  title=$(mpd-mixer display-status)
else
  title=$(playerctl status)
  if [ "$title" = "Playing" ]; then
    title=$(playerctl metadata -f "{{title}}")
  else
    title=$(mpd-mixer track-names | head -n 1)
  fi
fi

# title=$(echo "$title" | cut -c 1-31)
echo "$title"

# WIDTH=30
# percent=$(mpc | grep -oE "([0-9]+)%"  | tr -d \%)
# first=$(echo ".$percent * $WIDTH" | bc -l  | sed 's/\..*//')
# second=$((WIDTH - first))

# echo $(bs 'A1player.sh toggle; pkill -SIGRTMIN+10 i3blocks' ":$title $(bs "B$(colort -70 "$bg")" O${first} +o)$(bs Beef0f3 +o O${second})")

# done
