#!/bin/sh
# show status of org-pomodoro in a progress bar.
# tied to mpd, toggles on when working, off on break

calc() {
    echo "$*" | bc -l
}

time_offset_percent() {
    duration="$1" # minutes

    interval="$(calc ${duration} \* 60)"

    time_left="$(elisp '(format-time-string "%s" org-pomodoro-countdown)' | tr -d '"')"
    percent="$(calc "((${interval} - ${time_left}) / ${interval}) * 100" | sed 's/\..*//')"

    percent=${percent:-0}
    echo "${percent}"
}

progress() {
    mkb "$(time_offset_percent "$1")" 10 ◼ ◻ ◻
}

no_task() {
    mpc pause >/dev/null
    echo "No task!"
}

pomodoro_state="$(elisp org-pomodoro-state)"

case ${pomodoro_state} in
    :short-break) echo "Break $(progress 5)" ;;
    :long-break) echo "Long break $(progress 15)" ;;
    :pomodoro)
        mpc play >/dev/null
        task="$(elisp org-clock-current-task | tr -d '"')"
        echo "${task} $(progress 20)"
        ;;
    :none) no_task ;;
    *) no_task ;;
esac
