#!/bin/sh
# show status of org-pomodoro in a progress bar.
# tied to mpd, toggles on when working, off on break

WIDTH=60
org_task_status=$("$HOME/.wm/panel/lemons/org_task_elisp" $WIDTH)

topic=$(echo "$org_task_status" | awk -F \^ '{print $1}')
percent=$(echo "$org_task_status" | awk -F \^ '{print $2}')

if [ -z "$percent" ]; then
    echo "$topic"
else
    # echo "$topic $((percent / WIDTH))%"
    # todo: status bar colors
    echo "$topic $(bs "B$(colort -70 "$bg")" O$(( percent )) +o)$(bs Beef0f3 +o O$(($WIDTH - percent)) )"
fi
