#!/usr/bin/env bash

file="$HOME/sync/main/notes/pomodoro.org"
today=$(date +%Y-%m-%d)

date=${1:-today}

# pomo_minutes=$(grep "$date" "$file" | rg 'CLOCK.*=>  0:([0-9]+)' -or '$1' | jq -s 'add')

count=$(grep "$date" "$file" | grep 'CLOCK.*=>  0:2[3-7]' | wc -l)

for i in {1..4}; do
    if [ $i -le "$count" ]; then
	printf '☒'
    else
	printf '☐'
    fi
done

echo
