#!/usr/bin/env bash

file="$HOME/sync/main/notes/pomodoro.org"
today=$(date +'%Y-%m-%d')

date=${1:-$today}

# pomo_minutes=$(grep "$date" "$file" | rg 'CLOCK.*=>  0:([0-9]+)' -or '$1' | jq -s 'add')

count=$(grep "$date" "$file" | grep 'CLOCK.*=>  0:[12][3-9]' | wc -l)

if [ $count -gt 4 ]; then
    for i in {1..$count}; do
	printf '☒'
    done
else
    for i in {1..4}; do
	if [ $i -le "$count" ]; then
	    printf '☒'
	else
	    printf '☐'
	fi
    done
fi

echo
