#!/usr/bin/env bash

# ;; OK: underline when inactive but with wids
# ;; else just background color if active, no background if not turned on

# idea: need to show
notify-send "arst: $bg"

render() {
    current=$(bspc query -N -n)

    result=$(btags state-plain | while read -r line; do
	tag_name=$(echo "$line" | awk -F\| '{print $1}')
	name=$(echo "$line" | awk -F\| '{print $1}')
	active=$(echo "$line" | awk -F\| '{print $2}')
	color=$(echo "$line" | awk -F\| '{print $3}')
	wids=$(echo "$line" | awk -F\| '{print $4}')

	background=00000000

	if $active; then
	    if [ ! -z "$wids" ]; then
		background=$color
	    fi
	else
	    if [ ! -z "$wids" ]; then
		name="[${name}]"
	    fi
	fi

	name="  ${name}  "

	low=$(colort -l -40 $color)
	hats=
	if echo "$wids" | grep -q $current; then
	    hats='+o +u'
	    name="$(bs B$low O2)$(bs B$color ":${name}")$(bs B$low O2)"
	fi

	# height of the under/over determined from bar itself
	echo "$name" | bs U$low $hats \
	    "A3btags toggle-wids $tag_name \$(bspwindows)" \
	    "A1btags btags toggle $tag_name"
    done
    )

    echo "$result"
}

render

# bspc subscribe node_flag node_state node_geometry node_focus | while read -r trigger; do
#     # echo wew
#     render

# done
