#!/bin/sh

# ;; OK: underline when inactive but with wids
# ;; else just background color if active, no background if not turned on

# idea: need to show

while read -r _; do
    meta start
    meta set fg 111111
    current=$(bspc query -N -n)

    btags state-plain | while read -r line; do
	# meta reset
	# meta set bg \#00111111
	name=$(echo "$line" | awk -F\| '{print $1}')
	wids=$(echo "$line" | awk -F\| '{print $4}')
	color=$(echo "$line" | awk -F\| '{print $3}')

	display_name=''

        meta mouse_left btags toggle $name
        meta mouse_right 'notify-send btags toggle-wids $(bspwindows)'

	if echo "$line" | grep -q true; then
	    meta set bg \#$color
	else
	    meta set bg \#00111111
	    name="[${name}]"
	fi

	if [ -z "$wids" ]; then
	    meta set bg \#00111111
	fi

	if echo "$wids" | grep -q $current; then
	    name=">${name}<"
	fi

	# meta underline
	echo "   ${name}   "
    done

    meta end
    echo
done
