#!/usr/bin/env bash

(xtitle -s & bspc subscribe desktop_layout) | \
while read -r trigger; do
  title=$(xtitle -t 25)
  if [ "$(bspc query -T -d | jq -r .layout)" = "monocle" ]; then
    title=${title}\*
  fi
  printf '%s\n' "$title"
done

