#!/usr/bin/env bash
# neeasade's bspwmrc

. "$HOME/.sh.d/environment"
pathmunge "$HOME/.wm/scripts/visual"

{% for k,v in bspwm%}
bspc config {{k|name|replace:"-":"_"}} "{{v}}"{% endfor %}

for monitor in $(bspc query -M); do
    bspc monitor $monitor -d {{bspwm-meta.desktop-names}}
done

bspwm_kill_visual

# extensions may be defined in themes here:
{{bspwm-meta.bspwmrc-extend|safe}}

# initial wm startup actions ($xstart set in xinitrc)
if [ $(( $(date +%s) - ${xstart:-0} )) -lt 2 ]; then
    echo starting
    starting
    setsid $HOME/.wm/startup.sh &
    panelt
fi
