#!/usr/bin/env bash
# neeasade's bspwmrc

. "$HOME/.sh.d/environment"
pathmunge "$HOME/.wm/scripts/visual"

# panel_running=false
# if silent systemctl --user status panel; then
#     panel_running=true
# fi

# panel_padding=$(iif $relaunch_panel "{{panel.height}}+{{panel.gap}}" 0)
# side_padding=$(iif $gapped 0 {{border.width}})

# bspc config {{panel.position}}_padding $((side_padding + panel_padding))
# for side in left right {{panel.position-flipped}}; do
#     bspc config ${side}_padding $side_padding
# done

{% for k,v in bspwm%}
bspc config {{k|name|replace:"-":"_"}} "{{v}}"{% endfor %}

bspwm_kill_visual

for monitor in $(bspc query -M); do
    bspc monitor $monitor -d {{bspwm-meta.desktop-names}}
done

# extensions may be defined in themes here:
{{bspwm-meta.bspwmrc-extend|safe}}

# initial wm startup actions ($xstart set in xinitrc)
if [ $(( $(date +%s) - ${xstart:-0} )) -lt 2 ]; then
    echo starting
    starting
    setsid $HOME/.wm/startup.sh &
    panelt
fi
