#!/bin/sh
# panel_bar
# a script to interpret panel fifo information(workspace/window titles/system info)

# clickable area aliases
AC='%{A:'           # start click area
AB=':}'             # end click area cmd
AE='%{A}'           # end click area

# Shell commands for clickable areas
goto='bspc desktop -f'       # go to this desktop
cycle='bspc desktop -l next' # cycle tiled/monocle
winfocus='bspc window -f '   # focus on a window

while read -r line ; do
    case $line in
    S*)
        sys_infos="${line#?}"
    ;;
    T*)
        title=" %{F$pRest}"
        IFS='\'
        set -- ${line#?}
        while [ $# -gt 0 ] ; do
            item=$1
            name=${item#?}
            # form of $name will be window title // window id.
            # split and use for clickable focus areas
            winTitle="$(echo $name | grep -oE ".*//" | rev | cut -c 3- | rev)"
            winID="$(echo $name | grep -oE "//.*" | cut -c 3-)"
            if [ ! -z $winTitle ]; then
                case $item in
                    A*) title="${title}%{B$pBGActiveTab} %{F$pBG}$(printf %${pSLANT}s) ${winTitle} $(printf %${pSLANT}s)";; #active window
                    X*) title="${title}%{B$pBGInactiveTab}%{F$pFG}$(printf %${pSLANT}s)${AC}${winfocus} ${winID}${AB} ${winTitle} ${AE}$(printf %${pSLANT}s)";; #inactive window
                esac
            fi
            title="$title%{B$pBG} "
            shift
        done
    ;;
    W*)
        #setting the underline for everything with wm_info
        wm_infos="%{U$pBG+o} %{U$pBG+u}"
        IFS=':'
        set -- ${line#?}
        while [ $# -gt 0 ] ; do
            item=$1
            name=${item#?}
            case $item in
                O*) wm_infos="${wm_infos}%{B$pActive}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # active occupied desktop
                F*) wm_infos="${wm_infos}%{B$pActive}${AC}${goto} ${name}${AB} ${DF} ${AE}";; # active free desktop
                U*) wm_infos="${wm_infos}%{B$pUrgent}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # active urgent desktop
                o*) wm_infos="${wm_infos}%{B$pRest}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # inactive occupied desktop
                f*) wm_infos="${wm_infos}%{B$pBG}${AC}${goto} ${name}${AB} ${DF} ${AE}";; # inactive free desktop
                u*) wm_infos="${wm_infos}%{B$pUrgent}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # inactive urgent desktop
                L*) #wm_infos="${wm_infos}%{F$pRest}${AC}${cycle}${AB} $([[ $name == "T" ]] && echo $DT || echo $DM) ${AE}";; # Tiling/Monocle indicator, clickable toggle.
            esac
            wm_infos="$wm_infos%{B$pBG} "
            shift
        done
        wm_infos="$wm_infos%{B$pBG}"
    ;;
    esac
    printf "%s\n" "%{l}$title %{c}$wm_infos %{r}$sys_infos"
done
