# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d51b5579-ccc6-4e7b-b5d5-8a06898ca409";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A20A-267C";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f20e85be-ce18-474b-8b10-37d70b8f2a3d"; }
    ];

  fileSystems."/media/LIVEWIRE" =
    { device = "/dev/disk/by-uuid/2cf891b0-4adf-4fa0-bd80-e335303a1b13";
      fsType = "btrfs";
    };

  fileSystems."/media/CODERED" =
    { device = "/dev/disk/by-uuid/8c484b3d-b026-41f9-9cbe-dd551d1aead3";
      fsType = "ext4";
    };

  fileSystems."/media/VOLTAGE" =
    { device = "/dev/disk/by-uuid/00ebaffa-6c52-4422-8168-4a84622bad0c";
      fsType = "btrfs";
    };

  fileSystems."/media/KICKSTART" =
    { device = "/dev/disk/by-uuid/84894ed7-8e80-49a5-8951-ac61c23a6564";
      fsType = "btrfs";
    };

  nix.maxJobs = lib.mkDefault 8;
}
