#!/bin/sh
# 2lazy

persist=false
if [ "$1" = "-p" ]; then
    persist=true
    shift
fi

interval=$1
shift

while true; do
    echo "calling $*"
    if ! "$@"; then
	notify-send "script failed! $*"
	echo "failed! $*">&2
	# fail the service
	if $persist; then
	    exit 1
	fi
    fi

    sleep $interval
done
