#! /bin/sh

bspc config border_width        1
bspc config window_gap         12
bspc config top_padding 15

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor "DisplayPort-0" -n 1 -d I II III
bspc monitor "HDMI-0" -n 2 -d IV V VI
bspc monitor "DVI-1" -n 3 -d VII VIII IX X



bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

panel &
