#!/bin/sh
# This script will be sourced by themes and then have options overridden

# bspwm settings. Naming convention is b_<config_option>
b_border_width=3
b_window_gap=10
b_split_ratio=0.5
b_normal_border_color="$color0"
b_active_border_color="$color8"
b_focused_border_color="$foreground"
b_presel_feedback_color="$color8"
b_desktop_names="00 01 10 11"
b_monocle_window_percent=.55

# meant to be used for effects, like pulse or 2bspwm
b_bspwmrc_extend=""

# mkb script, l for loader
# ◼ ◻ ◻
l_complete="◼"
l_empty="◻"
l_sep="◻"
l_start=""
l_end=""

# Panel variables
p_format="dropdown:desktop:github:title|org_task|dynamicmpd:volume:weather:clock"
p_height=16                  # Panel height.
p_font_main="Droid Sans-8"   # Panel main font.
p_font_icon="FontAwesome-10" # Panel Icon font.
p_icon_enable=true           # toggle icon script output
p_gap=4                      # Gaps of panel off screen.
p_padding=4                  # number of pixels to pad panel information (sections/blocks) with
p_line=2 # width of the over/underlines
p_launch_cmd="$HOME/.wm/panel/lemonade" # The command to launch the panel

p_icon_handler="env printf \"\$icon_result\""

p_icon=unset              # icon color - used in qutebrowser completion, ACYL icons color
p_window_class="lemonbar" # window class to use in lemonade's juicer
p_position="top"          # panel position - top|bottom

# variables for desktop area
p_desktop_display_name=icon       # [icon|name] - display desktop names or DO/DF variables.
p_desktop_display_format=together # [together|separate] - show desktops in separate blocks or together in one block.
p_desktop_show_free=true          # option to show nothing for free desktops.
p_desktop_mode_toggle=false       # monocle/tiling toggle.
p_desktop_only_active=false       # only show the active desktop name
p_title_show_mode=monocle         # used by title.

# Panel colors
p_bg_normal="#ff$background"
p_fg_normal="#ff$foreground"
p_bg_active="$p_fg_normal"
p_fg_active="$p_bg_normal"
p_bg_inactive="$p_bg_normal"
p_fg_inactive="$p_fg_normal"

# panel icon colors - also used to color acyl icons, and qutebrowser match color.
# Workspace variables
p_desktop_occupied_label='[-]'
p_desktop_empty_label='[ ]'
p_desktop_tiling_label=''
p_desktop_monocle_label='M'

# default reload times for panel sections
p_mail_reload=30
p_desktop_reload="bspc subscribe"
p_title_reload="(xtitle -s & bspc subscribe desktop_layout)"
p_weather_reload=600
p_updates_reload=600
p_dropdown_reload="echo oneshot"
p_themeSwitch_reload="echo oneshot"
p_dynamicmpd_reload=0
p_github_reload=120

# default click actions for panel sections
p_themeSwitch_mouse_left="dzen.sh theme"
# p_org_task_mouse_left="elisp '(org-clock-goto)'; bspc node -f \$(xdotool search --onlyvisible --class Emacs)"
# p_org_task_mouse_right="elisp org-clock-current-task || bspc node -f \$(xdotool search --onlyvisible --class Emacs); elisp '(org-pomodoro)'"
p_dropdown_mouse_left="dzen.sh menu"
p_github_mouse_left="dzen.sh github"
p_circe_dms_mouse_left="dzen.sh circe"
p_clock_mouse_left="dzen.sh cal"
p_volume_scroll_down="ponymix decrease 5"
p_volume_scroll_up="ponymix increase 5"

p_mpd_scroll_up="mpc seek +00:00:02"
p_mpd_scroll_down="mpc seek -00:00:02"
p_mpd_mouse_left="player.sh toggle"
p_mpd_mouse_right="player.sh next"
p_mpd_mouse_middle="mpc clear"

p_dynamicmpd_scroll_up="mpc seek +00:00:02"
p_dynamicmpd_scroll_down="mpc seek -00:00:02"
p_dynamicmpd_mouse_left="player.sh toggle"
p_dynamicmpd_mouse_right="player.sh next"

emacs_theme="xresources"
emacs_powerline_scale="1.6"

# options
# alternate, arrow, arrow-fade, bar, box, brace, butt, chamfer, contour, curve, rounded, roundstub, wave, zigzag, utf-8.
emacs_powerline="bar"

# xst
st_font="Droid Sans Mono-10"
st_font_variable="Droid Sans-10"
st_cursorshape=2
st_cursorthickness=2

# padding
x_padding=10

GTK_FONT="Droid Sans 10" # GTK font to be used.

# dunst
d_font="Droid Sans 10" # Font used by dunst on startup
d_border_color="$b_normal_border_color"

# compton
c_frame_opacity="1.0"
c_shadow_opacity="0.4"
c_shadow="false"
c_shadow_radius="1"
c_shadow_offset_x="1"
c_shadow_offset_y="1"
c_shadow_red="0.0"
c_shadow_blue="0.0"
c_shadow_green="0.0"

c_fading="false"
c_fade_in_step="0.1"
c_fade_out_step="0.1"

# promptchar to be set for st and dmenu
PROMPT_CHAR='$'

tmux_statusbar="$(cat <<EOF
setw -g window-status-current-format '▄▄'
setw -g window-status-format '▄▄'
setw -g window-status-bg default
setw -g window-status-fg blue
setw -g window-status-current-bg default
setw -g window-status-current-fg white
setw -g window-status-current-attr bright

set-option -g status-position bottom
set -g status-bg default
set -g status-fg default
set -g status-justify right
set -g status-left ''
set -g status-right ''
EOF
)"

# mpd
music_dir="$HOME/Music"
mpd_dir="$HOME/.config/mpd"

# 2bspwm script overrides
border_width_in_normal=$(( border_width_current/2 ))
border_width_out_normal=$(( (border_width_current/2) + (border_width_current%2) ))
border_width_in_focused=$border_width_in_normal
border_width_out_focused=$border_width_out_normal

border_color_out_normal=$b_normal_border_color
border_color_out_focused=$b_focused_border_color

border_color_in_normal=$color2
border_color_in_focused=$color3

if type greaten>/dev/null; then
    border_color_in_normal=$(greaten $border_color_out_normal 30)
    border_color_in_focused=$(greaten $border_color_out_focused 30)
fi

# default template targets
# this allows themes to replace template files with different targets, by defining ${target}_template
for template in $(ls $HOME/.dotfiles/templates); do
    eval ${template}_template="$HOME/.dotfiles/templates/${template}"
done
