#!/usr/bin/env bash

prompt=${*:-select: }

# cheat a little: if called like regular dmenu ignore everything except -p
while :; do
    while getopts 'p:' flag 2>/dev/null; do
	case $flag in
	    p) prompt=$OPTARG;;
	    *) ;; # nop
	esac
    done
    ((OPTIND++))
    [ $OPTIND -gt $# ] && break
done

# wowie wow oh my
do_rofi() {
    read -r first_line;
    include=true
    if [[ $first_line == FEEDER_PID* ]]; then
	eval "$first_line"
	include=false
    fi

    {
	if $include; then
	    echo "$first_line"
	fi
	cat -
    } | rofi -dmenu -i -async-pre-read 0 -p "$prompt" -location 0 -yoffset -200 "$(theme getval p_font_main | sed 's/-/ /')" |
	while IFS=$'\n' read -r rofi_line; do
	    echo "$rofi_line"
	    if [ ! -z "$FEEDER_PID" ]; then
		kill -- -$(ps -o pgid= $FEEDER_PID | grep -o [0-9]*)
		# kill -- $FEEDER_PID
	    fi
	    break;
	done
}

if type rofi >/dev/null; then
    result=$(do_rofi)
elif elisp t >/dev/null; then
    result=$(cat - | emacs_dmenu "$prompt")
else
    real_dmenu=$(type -a dmenu | tail -n 1 | awk '{print $3}')
    result=$(cat - | "$real_dmenu" -p "$prompt")
fi

if [ -z "$result" ]; then
    echo
    exit 1
else
    echo "$result"
    exit 0
fi
