#!/bin/sh
# neeasade
# all switcher dmenu

switch=""
options=""

# windows
wids="$(bspc query -N -n .leaf.\!hidden)"
for wid in $wids; do
  title="window: $(xtitle $wid)"
  options="${options}"$'\n'"${title}"
  switch="$switch '$(echo "${title}" | sed "s#'#\'\\\'\'#g")') bspc node -f $wid;;"
done

# emacs buffers
buffers="$(
elisp '(-remove (lambda (buffer)
           (or
             (s-match "magit" buffer)
             (s-match "\*.*" buffer)
             )
           )
  (mapcar
    (function buffer-name)
    (buffer-list)
    )
  )
' | sed 's/" "/\n/g;s/("//;s/")//'
)"

for buffer in $buffers; do
  option="buffer: $buffer"
  options="${options}"$'\n'"${option}"
  switch="$switch '$(echo "${option}" | sed "s#'#\'\\\'\'#g")') select_action 'window: emacs' && elisp '(counsel-switch-to-buffer-or-window \"${buffer}\")';;"
done

# qutebrowser tabs
# TODO: learn qute ipc?

select_action() {
  # allow partial match for emacs switch match call
  # pause to rethink your life
  target="$(echo "$options" | grep "$@")"
  eval "case \"${target}\" in $switch esac"
}

switch="$switch *) ;;"

select_action "$(echo "$options" | dmenu "$@")"

# selection="$(echo "$options" | dmenu "$@")"
