#!/usr/bin/env bash
# neeasade
# window switcher dmenu

switch=""
wids="$(bspc query -N -n .leaf.\!hidden)"

for wid in $wids; do
  title="$(xtitle $wid | sed "s|'|\'\\\'\'|g")"
  switch="$switch '${title}') bspc node -f $wid;;"
done
switch="$switch *) ;;"

selection="$(echo $wids | xargs xtitle | dmenu "$@")"
eval "case \"$selection\" in $switch esac"
