#!/usr/bin/env bash
# neeasade
# depends: dmenu slop bspc

target=$*
if [ -z "$target" ]; then
    target=$(dmenu_path | eval dmenu "$@")
fi

bspc rule -a \* -o state=floating rectangle=$(slop -f "%g")
$target &
