#!/usr/bin/env bash
# neeasade
# depends: dmenu slop bspc

# get program name to launch using dmenu cache:
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
[ -d "$cachedir" ] && cache=$cachedir/dmenu_run || cache=$HOME/.dmenu_cache

program="$*"
if [ -z "$program" ]; then
    program=$(
    IFS=:
    if stest -dqr -n "$cache" $PATH; then
        stest -flx $PATH | sort -u | tee "$cache" | eval dmenu "$@"
    else
        eval dmenu "$@" < "$cache"
    fi
    )
fi

bspc rule -a \* -o state=floating rectangle=$(slop -f "%g")
$program &
