#!/usr/bin/env bash
# print dmenu dimensions for current monitor, and set prompt.

dim() {
     bspc query -T -m | jq .rectangle.$1
}

eval "$(theme get)"

width=$(bspc query -T -m | jq .rectangle.width)
width=$(echo .30 \* $width | bc | sed 's/\..*//')

# need a dmenu with xft font handling
# todo: txth -f "xft:${p_font_main}:style=Regular" -s $font_size "asdf"
line_height=15

lines=20
height=$((lines * line_height))

x=$(( ($(dim width) - width) / 2 ))
y=$(( ($(dim height) - height) / 3))

# trim alphas
p_fg_normal=$(colort -t "${p_fg_normal}")
p_fg_active=$(colort -t "${p_fg_active}")
p_bg_normal=$(colort -t "${p_bg_normal}")
p_bg_active=$(colort -t "${p_bg_active}")

echo "-nf #$p_fg_normal -nb #$p_bg_normal -sf #$p_fg_active -sb #$p_bg_active -fn \"${p_font_main}\" -y $y -x $x -h $line_height -w $width -l $lines -i -p ${1}:"
