#!/bin/sh
# toggle gaps on and off

want_gaps=$1
pad_px=$2

if [ -z "$want_gaps" ]; then
    # opposite of current status
    if [ $(bspc config window_gap) -le 0 ]; then
	want_gaps=true
    else
	want_gaps=false
    fi
fi

eval "$(theme -f "panel.height,x.padding,bspwm.border-width,bspwm.window-gap" -s)"
c() {
    bspc config "$@" &
}

padding() {
    pad=$1

    c left_padding $pad
    c right_padding $pad
    c bottom_padding $pad

    top_pad=$pad
    if silent systemctl --user status panel; then
	top_pad=$((pad + panel_height))
    fi

    c top_padding $top_pad
}

if $want_gaps; then
    c borderless_monocle false
    c window_gap "$bspwm_window_gap"
    padding 0

    ltheme bg
else
    if jget layout "$(bspc query -T -d)" | grep -q monocle; then
	if [ "$(bspc config left_monocle_padding)" = 0 ]; then
	    c borderless_monocle true
	    ltheme bg_plain &
	    pad_px=${pad_px:-$x_padding}
	fi
    fi

    c window_gap -$bspwm_border_width
    padding $((bspwm_border_width + pad_px))
fi

wait
