#!/bin/sh
# jump to some window by classname
# goal is to find last focused window by classname

# note: other way:
# bspc wm -d | jq '.focusHistory[] | select(.desktopId == '${current_desk}') | .nodeId' | sort -r
# for wid in $(); do echo nop done

# current_desk=$(printf "%d\n" $(bspc query -D -d))
current_desk=$(bspc query -D -d)

# WM_CLASS(STRING) = "emacs-26_3", "Emacs"
class=${*:-Emacs}

# todo: cache/don't retry checks
for wid in $(bspc wm -d | jq '.focusHistory[] | select(.desktopId == "'${current_desk}'") | .nodeId' | sort -r); do
    if xprop -id $wid | grep "^WM_CLASS" | grep "$class"; then
	echo bspc node -f $wid
	bspc node $wid -g hidden=off
	bspc node -f $wid
	exit 0
    fi
done

# if that fails, try all windows
for wid in $(bspc query -N -n .window | sort -r); do
    if xprop -id $wid | grep "^WM_CLASS" | grep "$class"; then
	echo bspc node -f $wid
	bspc node $wid -g hidden=off
	bspc node -f $wid
	exit 0
    fi
done
