#!/usr/bin/env dash
# Toggle the panel on/off

toggle=$1
if [ -z "$toggle" ]; then
    if systemctl --user status panel >/dev/null; then
	toggle=false
    else
	toggle=true
    fi
fi

if $toggle; then
    systemctl --user start panel
else
    systemctl --user stop panel
fi

# dunst pgrep's for panel
# commenting this out b/c resetting dunst clears the notification queue
# sleep 0.3
# theme refresh dunst
