#!/usr/bin/env dash
# Toggle the panel on/off

if systemctl --user status panel >/dev/null; then
    bspc config top_padding 0
    systemctl --user stop panel
else
    # top padding is set in the script
    systemctl --user start panel
fi

# dunst pgrep's for panel
sleep 0.3

theme refresh dunst
