#!/usr/bin/env dash
# neeasade
# needs even borders, 4 parts, middle is 2 parts

# set border widths, if odd outer is 1px larger
border_width=$(bspc config border_width)

if [ $border_width -lt 4 ]; then
    border_width=4
    bspc config border_width 4
fi

border_add=$((border_width%4))
border_width=$(( border_width - border_add ))
border_part=$((border_width/4))
border_middle=$((border_part * 2 + border_add))

focused=$(elisp -r '(tarp/get :primary)' | tr -d \#)
normal=$(elisp -r '(tarp/get :assumed)' | tr -d \#)

draw() {
    chwbb -i $border_part -o $border_part -m $border_middle -c $normal $(bspwindows inactive)

    # todo: idea: thicker inner part on focused windows
    # todo: chwbb should have options for specifying colors rather than just doing the thing itself
    chwbb -i $border_part -o $border_part -m $border_middle -c $focused $(bspwindows)
}

# initial draw
draw

# reactive draw
bspc subscribe node_geometry node_focus | while read msg; do
    draw
done
