#!/bin/sh

stripe_width=4
accent=4

border_width=$(bspc config border_width)
stripe_width=$((border_width / 2))

if [ $border_width -lt 8 ]; then
    border_width=8
    stripe_width=4
    bspc config border_width 8
fi

focused=$(bspc config focused_border_color | tr -d \#)
normal=$(bspc config normal_border_color | tr -d \#)
focused=$normal

bspc config focused_border_color \#$normal

draw() {
    outside=$step
    inside=$((border_width - outside - stripe_width))
    chwbn -b $outside -b $stripe_width -b $inside -c $normal -c $focused -c $normal $(bspwindows)

    if $reverse; then
	step=$((step-1))
	# [ $stripe_width -gt 0 ] && stripe_width=$((stripe_width-1))
	focused=$(greaten $focused $accent)
    else
	step=$((step+1))
	# stripe_width=$((stripe_width+1))
	focused=$(lessen $focused $accent)
    fi

    if $reverse; then
	[ $outside -ge 1 ] && reverse=true || reverse=false
    else
	[ $inside -le 1 ] && reverse=true || reverse=false
    fi
}

step=$((border_width-stripe_width))

while true; do
    draw
    sleep 0.05
done
