#!/bin/sh
# neeasade
# depends on: wmutils opt/chwb2
# needs even borders, 4 parts, middle is 2 parts

bspc config border_width 8
stripe_width=3
# for tinting
accent=3

# set border widths, if odd outer is 1px larger
border_width=$(bspc config border_width)

if [ $border_width -lt 4 ]; then
    border_width=4
fi

focused=$(bspc config focused_border_color | tr -d \#)
focused=cccccc
normal=$(bspc config normal_border_color | tr -d \#)
focused=$normal

bspc config focused_border_color \#$normal

draw() {
    outside=$step
    inside=$((border_width - outside - stripe_width))
    chwbn -b $outside -b $stripe_width -b $inside -c $normal -c $focused -c $normal $(bspwindows)

    if $reverse; then
	step=$((step-1))
	# [ $stripe_width -gt 0 ] && stripe_width=$((stripe_width-1))
	focused=$(greaten $focused 3)
    else
	step=$((step+1))
	# stripe_width=$((stripe_width+1))
	focused=$(lessen $focused 3)
    fi

    $reverse && \
	reverse=$(iif "[ $outside -ge 1 ]") || \
	    reverse=$(iif "[ $inside -le 1 ]")
}

step=$border_width
step=$((border_width-stripe_width))

while true; do
    draw
    sleep 0.05
done
