#!/usr/bin/env bash

. ~/.sh.d/environment

# fun ideas for later
# what if you could have groups of windows associated with a project
# or 'enabled' tags

# <monitor_id> <desktop_id> <ip_id> <node_id>
bspc subscribe node_add | while read -r event m d i wid; do
    current_class=$(xprop WM_CLASS -id $wid)
    current_name=$(xprop WM_NAME -id $wid)
    last_class=$(xprop WM_CLASS -id $(bspc query -N last -n))

    if echo "$current_name" | grep emacs_dmenu_frame; then
       continue
    fi

    # if "$current_class" | grep Steam; then
    # 	btags toggle-wids ^3 $wid
    # 	continue
    # fi

    if echo "$current_class" | grep -q qutebrowser; then
	vdo btags set-tag-on-wids ^2 $wid
	continue
    fi

    if echo "$last_class" | grep qutebrowser; then
	# if we are making an emacs window from browser assume it should be in code for now
	if echo "$current_class" | grep -v Emacs; then
	    # todo: only set if code visible
	    vdo btags set-tag-on-wids ^1 $wid
	    continue
	fi
    fi

    # todo: if current tag is not shown, don't copy over (because then double hidden flash)
    current_tag=$(btags get-tag "$(bspc query -N -n last)")
    if [ ! -z "$current_tag" ]; then
	btags set-tag-on-wids "$current_tag" $wid
    fi
done
