#!/bin/sh

# fun ideas for later
# what if you could have groups of windows associated with a project
# or 'enabled' tags

# <monitor_id> <desktop_id> <ip_id> <node_id>
bspc subscribe node_add | while read -r event m d i wid; do
    current_class=$(xprop WM_CLASS -id $wid)
    current_name=$(xprop WM_NAME -id $wid)
    last_class=$(xprop WM_CLASS -id $(bspc query -N last -n))

    if echo "$current_name" | grep emacs_dmenu_frame; then
       continue
    fi

    # if "$current-class" | grep Steam; then
    # 	btags toggle-wids ^3 $wid
    # 	continue
    # fi

    if echo "$current_class" | grep qutebrowser; then
	btags set-tag-on-wids net $wid
	continue
    fi

    if echo "$last_class" | grep qutebrowser; then
	# if we are making an emacs window from browser assume it should be in code for now
	if echo "$current_class" | grep Emacs; then
	    btags set-tag-on-wids code $wid
	    continue
	fi
    fi

    current_tag=$(btags get-tags "$(bspc query -N -n last)" | head -n 1)
    if [ ! -z "$current_tag" ]; then
	btags set-tag-on-wids "$current_tag" $wid
    fi
done
