#!/usr/bin/env bash
# neeasade
# stack windows to fake weight

key="below"

cleanup() {
    for wid in $(xdo id -N $key); do
	bspc node $wid -c
    done
}

launch() {
    setsid xst -c $key &
    setsid xst -c $key &
    setsid xst -c $key &
    setsid xst -c $key &
    # setsid xst -c $key &

    sleep 0.5

    wids=$(xdo id -N $key)
    for wid in $wids; do
	bspc node $wid -t floating
    done
}

not_together() {
    json=$(bspc query -T -n)
    state=$(jget -r state "$json")
    read x y w h < <(echo "$json" | jq -r '.client.'${state}'Rectangle | "\(.x) \(.y) \(.width) \(.height)"')

    w=$((w-40))
    x=$((x+20))

    # w=$((w-4))
    # x=$((x+2))
    h=$((h-2))

    read f_x f_y f_w f_h < <(bspc query -T -n $(echo "$wids" | head -n 1) | jq -r '.client.floatingRectangle | "\(.x) \(.y) \(.width) \(.height)"')

    for attr in x y w h; do
        eval "! [ "\$$attr" = "\$f_$attr" ] && return 1"
    done

    return 0
}

follow() {
    for wid in $wids; do
	xdo move -x $x -y $y $wid
	xdo resize -w $w -h $h $wid
    done
}

launch

trap 'cleanup' TERM INT

while read msg n b acted rest; do
    if ! grep -q "$acted" <<< "$wids"; then
	echo checking
	not_together || follow
    fi
done < <(bspc subscribe node_{geometry,focus})
