#!/usr/bin/env bash
# fake padding for X windows with thicc borders (terrible)

border_width=$(bspc config border_width)

pad_window() {
    # bspc config -n $2 border_width $((x_padding + border_width))
    chwbn -b $border_width -b $x_padding -c $1 -c $background_color $2
}

pad() {
    color=$1
    shift
    for wid in "$@"; do
	pad_window "$color" "$wid"
    done
}

draw() {
    # pad $border_color_active $(bspwindows)

    monocle=$(iif 'jget layout "$(bspc query -T -d)" | grep monocle')

    (
    	scale=1
    	x_padding=$((x_padding - scale))
    	border_width=$((border_width + scale))
    	pad $border_color_active $(bspwindows $(iif $monocle inactive active))
    )

    pad $border_color_normal $(bspwindows $(iif $monocle active inactive))

    # (
    # 	x_padding=$((x_padding - ))
    # 	border_width=$((border_width + scale))
    # 	# pad $border_color_active $(bspwindows)

    # 	# chwbn -b $border_width -b $x_padding \ -c $border_color_active \ -c $background_color \ $(bspwindows)
    # )

}

bspc config border_width $((x_padding))

draw

bspc subscribe node_state node_geometry node_focus | while read msg; do
    draw
done
