#!/usr/bin/env dash
# print dmenu dimentions for current monitor, and set prompt.
# colors are set by Xresources.

# get gap values
. ~/.bspwm_theme

[ $(bspc config window_gap) -le 0 ] && p_gap=0

p_width=$(bspc query -T -m | jq -r '.rectangle.width')
p_width=$(( p_width - (p_gap + p_gap) ))

echo "-y $p_gap -x $p_gap -h $p_height -w $p_width -i -q -p \"${PROMPT_CHAR}\""
