#!/usr/bin/env bash
# This is a dmenu wrapper for http://www.passwordstore.org/

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
    typeit=1
    shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

pass=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n $pass ]] || exit

if [[ $typeit -eq 0 ]]; then
    pass show -c "$pass" 2>/dev/null
else
    pass show "$pass" |
        awk 'BEGIN{ORS=""} {print; exit}' |
        xdotool type --clearmodifiers --file -
fi

