#!/usr/bin/env dash
# print dmenu dimentions for current monitor, and set prompt.
# colors are set by Xresources.

# get gap values
. ~/.bspwm_theme

[ $(bspc config window_gap) -le 0 ] && PANEL_GAP=0

PANEL_WIDTH=$(bspc query -T -m | jq -r '.rectangle.width')
PANEL_WIDTH=$(( PANEL_WIDTH - (PANEL_GAP + PANEL_GAP) ))

echo "-y $PANEL_GAP -x $PANEL_GAP -h $PANEL_HEIGHT -w $PANEL_WIDTH -i -q -p \"${PROMPT_CHAR}\""
