#!/usr/bin/env bash
# Load a bspwm theme based on argument
# This loads settings for: bspwm, xst, tmux, vim, lemonbar, GTK/Icons, qutebrowser, dunst.
# This makes heavy use of a posix implementation of mustache templates.

targetTheme="$HOME/.wm/themes/${1}.bspwm_theme"
[ -f "$targetTheme" ] || exit 1

set -a

unset block
rm $HOME/.bspwm_theme
ln -s "$targetTheme" "$HOME/.bspwm_theme"

. "$HOME/.bspwm_theme"
. "$HOME/.wm/templates/mustache.sh"

# adjust pIcon to theme (rel for panel, acyl, qutebrowser.)
if [ "$p_icon" = "unset" ]; then
    if colort -c "$p_bg_active"; then
        p_icon=$(colort -c "$p_fg_inactive" && colort -l -40 "$p_fg_inactive" || colort -l 40 "$p_fg_inactive")
        [ $? -ne 0 ] && p_icon=$(colort -c "$p_fg_inactive" && colort 50 "$p_fg_inactive" || colort -50 "$p_fg_inactive")
    else
        # light, assume invert
        p_icon=$(colort -c "$p_fg_inactive" && colort -l 60 "$p_fg_inactive" || colort -l -60 "$p_fg_inactive")
        [ $? -ne 0 ] && p_icon=$(colort -c "$p_fg_inactive" && colort -60 "$p_fg_inactive" || colort 60 "$p_fg_inactive")
    fi
fi

# mustache args
margs() {
    mustache < "$HOME/.wm/templates/$1" > "$HOME/$2"
}

trimAlphas() {
    for target in active inactive normal; do
        eval p_fg_$target=$(eval colort -t "\$p_fg_$target")
        eval p_bg_$target=$(eval colort -t "\$p_bg_$target")
    done

    p_icon=$(colort -t "$p_icon")
}

# tmux
load_tmux() {
    tmux source-file $HOME/.tmux.conf > /dev/null 2>&1
}

load_bg() {
    eval $BG_COMMAND
}

# also loads term.
load_xresources() {
    margs Xresources .Xresources

    # handle any color definitions through 255
    for i in `seq 0 255`; do
        eval "[ ! -z \$color$i ] && echo \*.color$i: \#\$color$i >> $HOME/.Xresources"
    done

    xrdb $HOME/.Xresources

    # tell all xsts to reload their theme:
    killall -s USR1 st
}

# Keep the current gap setting and reload bspwm
load_bspwm() {
    [ ! -d "$HOME/.wm/panel/juicers" ] && mkdir $HOME/.wm/panel/juicers

    margs juicer .wm/panel/juicers/juicer

    # custom reload values:
    p_mail_reload=30
    p_desktop_reload="bspc subscribe"
    p_title_reload="xtitle -s"
    p_weather_reload=600
    p_updates_reload=600
    p_dropdown_reload="echo oneshot"
    p_themeSwitch_reload="echo oneshot"

    # note all lemons, generate them.
    lemons=$(echo $p_format | tr ':|' ' ');
    IFS=' '
    for lemon in $lemons; do
        colorchange.sh "$lemon" "$(eval "echo \${p_${lemon}_reload}")" >> ~/.wm/panel/juicers/juicer
        echo "" >> ~/.wm/panel/juicers/juicer
    done
    IFS=

    [ $(bspc config window_gap) -le 0 ] && export BSPWM_GAPS=false
    "$HOME/.wm/bspwmrc"
}

# vim reload
load_vim() {
    VIMS=`vim --serverlist`
    for vim in $VIMS; do
        vim --servername $vim --remote-send '<Esc>:so $MYVIMRC<CR>' &
    done
}

# GTK (make theme if it does not exist, then reload)
load_gtk() {
    trimAlphas
    margs gtkrc .gtkrc-2.0

    if [ ! -d "$HOME/.themes/$THEME_NAME" ]; then
        target="$(mktemp)"
        mustache < $HOME/.wm/templates/oomox > $target
        oomox-cli -o "$THEME_NAME" "$target"
    fi

    # icon color(ACYL)
    $HOME/.icons/acyl/icon.sh "#$p_icon"

    # reload
    gtkrc-reload &

    # set a place to reference active theme for newly launched GTK3 programs.
    echo "$THEME_NAME" > $HOME/.themes/ACTIVE_THEME
}

# qutebrowser
load_qutebrowser() {
    trimAlphas

    echo $p_font_main | grep -q Bold && p_font_main_bold="bold"
    p_font_main_size="$(echo $p_font_main | grep -Eo '[0-9]+')"
    p_font_main="$(echo $p_font_main | sed 's/-.*//')"
    p_height="$(( ($p_height-10) / 2 ))"

    margs qutebrowser .config/qutebrowser/qutebrowser.conf
}

# dunst
load_dunst() {
    trimAlphas
    [ $b_border_width -gt 4 ] && b_border_width=$(( $b_border_width/2 ))
    killall dunst

    margs dunstrc .config/dunst/dunstrc
    dunst &
}

# do the thing
for conf in tmux xresources bspwm bg vim gtk dunst qutebrowser; do
    load_$conf &
done
