colors = ['#E8EBEC', '#006E96', '#007C00', '#C38418', '#0065C8', '#407EE7', '#C6007F', '#444748', '#6A6D6E', '#006E96', '#007C00', '#C38418', '#0065C8', '#407EE7', '#C6007F', '#444748']

color.cursor = "#0065c8"
color.normal.background = "#e8ebec"
color.normal.foreground = "#444748"
color.normal.faded = "#6a6d6e"
color.normal.primary = "#c6007f"
color.normal.alt = "#006e96"
color.normal.strings = "#007c00"
color.normal.assumed = "#0065c8"
color.weak.background = "#d5d6d7"
color.weak.foreground = "#393a3b"
color.weak.faded = "#5f6061"
color.weak.primary = "#ba0073"
color.weak.alt = "#00668e"
color.weak.strings = "#007400"
color.weak.assumed = "#005dc0"
color.strong.background = "#ccc9ca"
color.strong.foreground = "#343132"
color.strong.faded = "#5a5758"
color.strong.primary = "#ac0065"
color.strong.alt = "#005e86"
color.strong.strings = "#006c00"
color.strong.assumed = "#0053b6"
color.focused.background = "#a4cfed"
color.focused.foreground = "#093553"
color.focused.faded = "#305b79"
color.focused.primary = "#ac0065"
color.focused.alt = "#005e86"
color.focused.strings = "#006c00"
color.focused.assumed = "#0053b6"
